//! The golden vector round trip.
//!
//! Covers AC2 (every message type encodes to its committed vector and decodes
//! back to the same field values) and AC8 (the vectors are read from committed
//! files and are never regenerated by the suite).

mod common;

use std::fs;
use std::time::SystemTime;

use chorus_protocol::{decode_frame, encode, FrameOutcome, MessageType};

use common::{fixture_dir, load_vector};

#[test]
fn every_catalogued_message_type_has_a_committed_vector() {
    assert_eq!(
        MessageType::ALL.len(),
        2,
        "the catalog changed; every type needs its own committed vector"
    );
    for message_type in MessageType::ALL {
        let vector = load_vector(message_type);
        assert!(
            !vector.frame.is_empty(),
            "{}.hex is empty",
            message_type.name()
        );
    }
}

#[test]
fn encoder_reproduces_every_committed_vector() {
    for message_type in MessageType::ALL {
        let vector = load_vector(message_type);
        let encoded = encode(&vector.message)
            .unwrap_or_else(|e| panic!("{} canonical input must encode: {}", vector.name, e));
        assert_eq!(
            encoded,
            vector.frame,
            "{}: encoder output differs from the committed vector\n encoded: {}\n golden:  {}",
            vector.name,
            hex(&encoded),
            hex(&vector.frame)
        );
    }
}

#[test]
fn decoder_recovers_every_committed_vector() {
    for message_type in MessageType::ALL {
        let vector = load_vector(message_type);
        let result = decode_frame(&vector.frame);
        assert_eq!(
            result.consumed,
            vector.frame.len(),
            "{}: the vector is exactly one frame",
            vector.name
        );
        match result.outcome {
            FrameOutcome::Decoded(message) => assert_eq!(
                message, vector.message,
                "{}: decoded fields differ from the canonical input",
                vector.name
            ),
            other => panic!("{}: the committed vector must decode, got {:?}", vector.name, other),
        }
    }
}

#[test]
fn frame_headers_of_the_committed_vectors_are_what_the_catalog_says() {
    for message_type in MessageType::ALL {
        let vector = load_vector(message_type);
        assert_eq!(
            vector.frame[0],
            message_type.to_wire(),
            "{}: first byte is the message type",
            vector.name
        );
        let declared = u16::from_be_bytes([vector.frame[1], vector.frame[2]]) as usize;
        assert_eq!(
            declared,
            vector.frame.len() - 3,
            "{}: the length field describes the payload that follows",
            vector.name
        );
        assert!(
            declared >= message_type.min_payload_len(),
            "{}: the vector is at least this type's minimum",
            vector.name
        );
    }
}

#[test]
fn fixtures_are_not_rewritten_by_the_suite() {
    // Fingerprint every fixture file, run the whole round trip, fingerprint
    // again. A suite that regenerated its own golden vectors would fail here.
    let before = fingerprint_fixtures();
    assert!(
        before.len() >= 4,
        "expected a .hex and a .fields per message type, found {} files",
        before.len()
    );

    for message_type in MessageType::ALL {
        let vector = load_vector(message_type);
        let encoded = encode(&vector.message).expect("canonical input encodes");
        assert_eq!(encoded, vector.frame);
        let result = decode_frame(&vector.frame);
        assert!(result.outcome.is_decoded());
    }

    let after = fingerprint_fixtures();
    assert_eq!(
        before, after,
        "a fixture file changed while the suite ran; golden vectors are committed, not generated"
    );
}

fn fingerprint_fixtures() -> Vec<(String, u64, SystemTime)> {
    let mut out = Vec::new();
    let dir = fixture_dir();
    for entry in fs::read_dir(&dir).expect("the fixture directory exists") {
        let entry = entry.expect("readable directory entry");
        let meta = entry.metadata().expect("readable metadata");
        if !meta.is_file() {
            continue;
        }
        out.push((
            entry.file_name().to_string_lossy().into_owned(),
            meta.len(),
            meta.modified().expect("a modification time"),
        ));
    }
    out.sort();
    out
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 3);
    for byte in bytes {
        if !out.is_empty() {
            out.push(' ');
        }
        out.push_str(&format!("{:02X}", byte));
    }
    out
}
