// docs/comment-density-record.md, read as data rather than as prose.
//
// The record is the thing that declares what the ceiling is; the gate carries
// the numbers it enforces. They have to agree or one of them is a story about
// the other. The same reading gives the before column its meaning: a row whose
// two code-line counts differ says a trim moved a code token, which is the one
// thing a trim may not do.

use std::fmt::Write as _;

use crate::count::{format_tenths, tenths, Config};
use crate::sweep::Sweep;

// The record carries measurements and not a story, so the generated region is
// counts and nothing else. What the ceiling IS lives in the hand-written half,
// which is what check() reads it out of and refuses on.

pub const BEGIN: &str =
    "<!-- comment-density: everything below is generated by `make comment-density-record` -->";
pub const END: &str = "<!-- comment-density: end of the generated measurement -->";

const CEILING_KEY: &str = "- ceiling:";
const WARN_KEY: &str = "- warn band:";
const MINIMUM_KEY: &str = "- minimum counted lines:";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Cell {
    pub prose: usize,
    pub code: usize,
}

impl Cell {
    pub fn tenths(&self) -> u32 {
        tenths(self.prose, self.code)
    }
}

#[derive(Debug, Clone)]
pub struct Row {
    pub path: String,
    pub before: Option<Cell>,
    pub before_ratio: Option<u32>,
    pub after: Cell,
    pub after_ratio: u32,
}

#[derive(Debug, Clone, Default)]
pub struct Record {
    pub ceiling: Option<u32>,
    pub warn: Option<u32>,
    pub minimum: Option<usize>,
    pub rows: Vec<Row>,
}

pub fn parse(text: &str) -> Record {
    let mut record = Record::default();
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix(CEILING_KEY) {
            record.ceiling = percent(rest);
        } else if let Some(rest) = line.strip_prefix(WARN_KEY) {
            record.warn = percent(rest);
        } else if let Some(rest) = line.strip_prefix(MINIMUM_KEY) {
            record.minimum = rest.trim().parse().ok();
        } else if let Some(row) = row(line) {
            record.rows.push(row);
        }
    }
    record
}

fn percent(text: &str) -> Option<u32> {
    text.trim().trim_end_matches('%').trim().parse().ok()
}

fn ratio(text: &str) -> Option<u32> {
    let text = text.trim().trim_end_matches('%');
    let (whole, fraction) = text.split_once('.')?;
    let whole: u32 = whole.trim().parse().ok()?;
    let fraction: u32 = fraction.trim().parse().ok()?;
    Some(whole * 10 + fraction)
}

fn row(line: &str) -> Option<Row> {
    if !line.starts_with('|') {
        return None;
    }
    let cells: Vec<&str> = line.trim_matches('|').split('|').map(|cell| cell.trim()).collect();
    if cells.len() != 7 || !cells[0].ends_with(".rs") {
        return None;
    }
    let before = if cells[1] == "-" && cells[2] == "-" {
        None
    } else {
        Some(Cell { prose: cells[1].parse().ok()?, code: cells[2].parse().ok()? })
    };
    Some(Row {
        path: cells[0].to_string(),
        before,
        before_ratio: if before.is_none() { None } else { ratio(cells[3]) },
        after: Cell { prose: cells[4].parse().ok()?, code: cells[5].parse().ok()? },
        after_ratio: ratio(cells[6])?,
    })
}

// Every way the record and the gate can disagree, named one per line. The
// caller turns a non-empty list into the record-disagreement exit code.
pub fn check(record: &Record, sweep: &Sweep, cfg: &Config) -> Vec<String> {
    let mut found = Vec::new();
    match record.ceiling {
        None => found.push("the record declares no ceiling, so the gate has nothing to enforce"
            .to_string()),
        Some(value) if value != cfg.ceiling_percent => found.push(format!(
            "the record declares a {}% ceiling and the gate enforces {}%",
            value, cfg.ceiling_percent
        )),
        Some(_) => {}
    }
    match record.warn {
        None => found.push("the record declares no warn band".to_string()),
        Some(value) if value != cfg.warn_percent => found.push(format!(
            "the record declares a {}% warn band and the gate enforces {}%",
            value, cfg.warn_percent
        )),
        Some(_) => {}
    }
    match record.minimum {
        None => found.push("the record declares no minimum counted lines".to_string()),
        Some(value) if value != cfg.minimum_counted_lines => found.push(format!(
            "the record declares a {}-line minimum and the gate enforces {}",
            value, cfg.minimum_counted_lines
        )),
        Some(_) => {}
    }

    let live: Vec<(&str, Cell)> = sweep
        .measured()
        .map(|(path, counts)| (path, Cell { prose: counts.prose, code: counts.code }))
        .collect();

    for row in &record.rows {
        let Some((_, cell)) = live.iter().find(|(path, _)| *path == row.path) else {
            found.push(format!(
                "the row for {} names a path that is not a tracked .rs file this gate measures",
                row.path
            ));
            continue;
        };
        if let Some(before) = row.before {
            if before.code != row.after.code {
                found.push(format!(
                    "the row for {} carries {} code lines before and {} after, so the trim moved \
                     a code token",
                    row.path, before.code, row.after.code
                ));
            }
            if row.before_ratio != Some(before.tenths()) {
                found.push(format!(
                    "the row for {} states a before ratio its own before counts do not give",
                    row.path
                ));
            }
        }
        if row.after != *cell {
            found.push(format!(
                "the row for {} carries prose={} code={} and the tree measures prose={} code={}",
                row.path, row.after.prose, row.after.code, cell.prose, cell.code
            ));
        }
        if row.after_ratio != row.after.tenths() {
            found.push(format!(
                "the row for {} states an after ratio its own after counts do not give",
                row.path
            ));
        }
    }

    for (path, _) in &live {
        if !record.rows.iter().any(|row| row.path == *path) {
            found.push(format!("{path} is measured and the record lists no row for it"));
        }
    }
    found
}

// Rewrite the generated region. The before column is carried over untouched
// unless baseline is asked for, which is what task-ordering makes possible: the
// untrimmed tree is measured and committed before anything is trimmed.
pub fn render(existing: &str, sweep: &Sweep, baseline: bool) -> Result<String, String> {
    let head = existing.find(BEGIN).ok_or_else(|| format!("the record carries no {BEGIN:?}"))?;
    let tail = existing.find(END).ok_or_else(|| format!("the record carries no {END:?}"))?;
    let previous = parse(existing);

    let mut body = String::new();
    let _ = writeln!(body, "{BEGIN}");
    let _ = writeln!(body);

    let mut rows: Vec<Row> = Vec::new();
    for (path, counts) in sweep.measured() {
        let after = Cell { prose: counts.prose, code: counts.code };
        let before = if baseline {
            Some(after)
        } else {
            previous.rows.iter().find(|row| row.path == path).and_then(|row| row.before)
        };
        rows.push(Row {
            path: path.to_string(),
            before,
            before_ratio: before.map(|cell| cell.tenths()),
            after,
            after_ratio: after.tenths(),
        });
    }

    let untrimmed: Vec<&Row> = rows.iter().filter(|row| row.before.is_some()).collect();
    let before_prose: usize = untrimmed.iter().map(|row| row.before.unwrap().prose).sum();
    let before_code: usize = untrimmed.iter().map(|row| row.before.unwrap().code).sum();
    let (after_prose, after_code) = sweep.aggregate();

    let _ = writeln!(body, "| distribution | files | prose lines | code lines | ratio |");
    let _ = writeln!(body, "|---|---|---|---|---|");
    let _ = writeln!(
        body,
        "| untrimmed | {} | {} | {} | {} |",
        untrimmed.len(),
        before_prose,
        before_code,
        format_tenths(tenths(before_prose, before_code))
    );
    let _ = writeln!(
        body,
        "| at this change's head | {} | {} | {} | {} |",
        rows.len(),
        after_prose,
        after_code,
        format_tenths(tenths(after_prose, after_code))
    );
    let _ = writeln!(body);

    let _ = writeln!(
        body,
        "| file | prose before | code before | ratio before | prose after | code after | ratio \
         after |"
    );
    let _ = writeln!(body, "|---|---|---|---|---|---|---|");
    for row in &rows {
        match row.before {
            Some(before) => {
                let _ = writeln!(
                    body,
                    "| {} | {} | {} | {} | {} | {} | {} |",
                    row.path,
                    before.prose,
                    before.code,
                    format_tenths(before.tenths()),
                    row.after.prose,
                    row.after.code,
                    format_tenths(row.after_ratio)
                );
            }
            None => {
                let _ = writeln!(
                    body,
                    "| {} | - | - | - | {} | {} | {} |",
                    row.path,
                    row.after.prose,
                    row.after.code,
                    format_tenths(row.after_ratio)
                );
            }
        }
    }
    let _ = writeln!(body);

    Ok(format!("{}{}{}", &existing[..head], body, &existing[tail..]))
}
