#!/usr/bin/env python3
"""The concurrent-streams measurement's helper (tools/concurrent-streams-run.sh, proposal
P11, decision K76): what K independent streams cost a running chorus-server in CPU and
memory, read off /proc.

Standard library only, plus the pinned reference programs for `media`. Subcommands:

- `media`: make the test signals. One 44.1 kHz 16-bit stereo signal (two sines and two
  independently seeded pink noises, one mix per channel, generated by the pinned ffmpeg's
  `sine` and `anoisesrc` sources, so it is the same on every run) encoded once per settled
  input format at a bitrate a household library really holds (the table ENCODES below).
  The programs come from the conda-forge prefix `make decode-fixtures` uses
  (tools/decode-fixtures/generate.py holds the pins and checks them; this command calls
  that check). Every program is used as a program; none of their source was opened.
- `serve`: a local HTTP media server (Range honoured, one thread per connection), the
  stand-in for a household's media server. It is another process, so its cost is not in
  the server's figures.
- `measure`: the scripted UPnP control point and the sampler. It finds the renderers the
  way a control point does (a search, each description), plays the same file on K of them
  (each renderer is one room, so each is its own stream through its own player thread),
  waits until every one is PLAYING and has settled, and reads /proc at both ends of a
  fixed window: per thread `utime + stime` (/proc/<pid>/task/<tid>/stat, clock ticks) and
  the scheduler's own run time (/proc/<pid>/task/<tid>/schedstat, nanoseconds, the finer
  figure), and for the process VmRSS, RssAnon, RssFile, VmHWM, VmSize (/proc/<pid>/status),
  Rss, Pss, Pss_Anon (/proc/<pid>/smaps_rollup) and the size of every mapping it may touch
  (/proc/<pid>/maps). Threads are told apart by the roles the
  server itself prints in its scheduling report (`thread role=<role> tid=<tid>`): the
  server does not name its threads for the kernel, and needs no change for this.
  With `--subscribe` it first subscribes, as one control point, to every service of every
  renderer and receives the events on a loopback callback.
- `probe`: the decoders alone: `chorus-server --probe-media` on each file (it decodes the
  file to its end and starts nothing else), the child's own CPU time from wait4. The
  `maxrss_kb` column it also writes is NOT the decoder's memory: it came out the same for
  every format (the forked interpreter's own peak before the exec), so no table uses it.
- `summary`: the report's tables (Markdown) from one or more runs' `windows.jsonl`.

Every interval here is CLOCK_MONOTONIC (`time.monotonic_ns`). Nothing here is timing
evidence: these are CPU and memory figures of a shared host.
"""

import argparse
import hashlib
import http.client
import http.server
import importlib.util
import json
import os
import re
import socket
import socketserver
import subprocess
import sys
import threading
import time
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))
SECONDS_DEFAULT = 130
DEVICE = "urn:schemas-upnp-org:device:MediaRenderer:1"
AVT = "urn:schemas-upnp-org:service:AVTransport:1"
SSDP_HOST = "239.255.255.250:1900"

# name, extension, Content-Type, what the report calls it. The encoder lines are in
# `make_media`; the bitrates are the upper end of what a library holds (ASSUMED: MP3 at
# 320 kbit/s constant, Vorbis quality 6, Opus 128 kbit/s, FLAC and ALAC at their
# encoders' default effort), so decode cost is not understated.
ENCODES = [
    ("wav48", "wav", "audio/wav", "WAV, 16-bit stereo 48 kHz (the server's own rate: no decoder work, no resampling)"),
    ("wav", "wav", "audio/wav", "WAV, 16-bit stereo 44.1 kHz"),
    ("flac", "flac", "audio/flac", "FLAC level 5, 16-bit stereo 44.1 kHz"),
    ("mp3", "mp3", "audio/mpeg", "MP3 320 kbit/s CBR, stereo 44.1 kHz"),
    ("vorbis", "ogg", "audio/ogg", "Ogg Vorbis quality 6, stereo 44.1 kHz"),
    ("opus", "opus", "audio/ogg", "Ogg Opus 128 kbit/s, stereo 48 kHz"),
    ("alac", "m4a", "audio/mp4", "ALAC in MP4 (moov first), 16-bit stereo 44.1 kHz"),
]


def die(msg):
    sys.exit(f"concurrent-streams: {msg}")


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


# --- media -----------------------------------------------------------------------


def make_media(args):
    spec = importlib.util.spec_from_file_location(
        "generate", os.path.join(os.path.dirname(HERE), "decode-fixtures", "generate.py")
    )
    gen = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gen)
    gen.check_prefix(args.prefix)
    tool = lambda name: os.path.join(args.prefix, "bin", name)  # noqa: E731
    os.makedirs(args.out, exist_ok=True)
    secs = str(args.seconds)
    exact = ["-fflags", "+bitexact", "-flags:a", "+bitexact"]

    def run(cmd):
        r = subprocess.run(cmd, capture_output=True)
        if r.returncode != 0:
            die(f"{' '.join(cmd)}\n{r.stderr.decode(errors='replace')[-2000:]}")

    out = lambda name, ext: os.path.join(args.out, f"{name}.{ext}")  # noqa: E731
    wav = out("wav", "wav")
    graph = (
        "[0][2]amix=inputs=2:normalize=0[l];[1][3]amix=inputs=2:normalize=0[r];"
        "[l][r]join=inputs=2:channel_layout=stereo"
    )
    run([tool("ffmpeg"), "-v", "error", "-y",
         "-f", "lavfi", "-i", f"sine=frequency=440:sample_rate=44100:duration={secs}",
         "-f", "lavfi", "-i", f"sine=frequency=660:sample_rate=44100:duration={secs}",
         "-f", "lavfi", "-i", f"anoisesrc=color=pink:sample_rate=44100:duration={secs}:seed=17:amplitude=0.3",
         "-f", "lavfi", "-i", f"anoisesrc=color=pink:sample_rate=44100:duration={secs}:seed=71:amplitude=0.3",
         "-filter_complex", graph, *exact, "-c:a", "pcm_s16le", wav])
    run([tool("ffmpeg"), "-v", "error", "-y", "-i", wav, *exact, "-ar", "48000", "-c:a", "pcm_s16le", out("wav48", "wav")])
    run([tool("flac"), "--silent", "--force", "-5", "-o", out("flac", "flac"), wav])
    run([tool("lame"), "--quiet", "--cbr", "-b", "320", "--noreplaygain", wav, out("mp3", "mp3")])
    run([tool("ffmpeg"), "-v", "error", "-y", "-i", wav, *exact, "-c:a", "libvorbis", "-q:a", "6",
         out("vorbis", "ogg")])
    run([tool("ffmpeg"), "-v", "error", "-y", "-i", wav, *exact, "-c:a", "libopus", "-b:a", "128k",
         "-f", "opus", out("opus", "opus")])
    run([tool("ffmpeg"), "-v", "error", "-y", "-i", wav, *exact, "-c:a", "alac", "-sample_fmt", "s16p",
         "-movflags", "+faststart", out("alac", "m4a")])
    with open(os.path.join(args.out, "media.tsv"), "w") as f:
        f.write("format\tfile\tbytes\tkbit_per_s\tsha256\twhat\n")
        for name, ext, _, what in ENCODES:
            path = out(name, ext)
            size = os.path.getsize(path)
            f.write(f"{name}\t{name}.{ext}\t{size}\t{size * 8 / args.seconds / 1000:.0f}\t{sha256(path)}\t{what}\n")
    sys.stdout.write(open(os.path.join(args.out, "media.tsv")).read())


# --- the media server ---------------------------------------------------------------


class Media(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    root = "."

    def log_message(self, *_):
        pass

    def do_HEAD(self):
        self.answer(False)

    def do_GET(self):
        self.answer(True)

    def answer(self, body):
        name = self.path.split("?")[0].lstrip("/")
        types = {f"{n}.{e}": t for n, e, t, _ in ENCODES}
        path = os.path.join(self.root, name)
        if name not in types or not os.path.isfile(path):
            self.send_response(404)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        size = os.path.getsize(path)
        start = 0
        m = re.match(r"bytes=(\d+)-(\d*)$", self.headers.get("Range", ""))
        end = size - 1
        if m and int(m.group(1)) < size:
            start = int(m.group(1))
            if m.group(2):
                end = min(int(m.group(2)), size - 1)
            self.send_response(206)
            self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
        else:
            self.send_response(200)
        self.send_header("Content-Type", types[name])
        self.send_header("Accept-Ranges", "bytes")
        self.send_header("Content-Length", str(end - start + 1))
        self.send_header("Connection", "close")
        self.end_headers()
        self.close_connection = True
        if not body:
            return
        with open(path, "rb") as f:
            f.seek(start)
            left = end - start + 1
            try:
                while left > 0:
                    block = f.read(min(65536, left))
                    if not block:
                        break
                    self.wfile.write(block)
                    left -= len(block)
            except (BrokenPipeError, ConnectionResetError):
                pass


class Threaded(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True

    def handle_error(self, request, client_address):
        # A peer that closes first (the server after an event, a player that stops a
        # fetch) is not an error of the measurement.
        pass


def serve(args):
    Media.root = args.dir
    server = Threaded(("127.0.0.1", 0), Media)
    with open(args.port_file + ".tmp", "w") as f:
        f.write(str(server.server_address[1]))
    os.replace(args.port_file + ".tmp", args.port_file)
    server.serve_forever()


# --- /proc ---------------------------------------------------------------------------


def stat_ticks(path):
    """utime + stime of a /proc stat file, in clock ticks (fields 14 and 15; the comm
    field may hold spaces, so the split starts after its closing parenthesis)."""
    text = open(path).read()
    rest = text[text.rindex(")") + 2:].split()
    return int(rest[11]) + int(rest[12])


def kb_fields(path, names):
    out = {}
    for line in open(path):
        key, _, value = line.partition(":")
        if key in names:
            out[key] = int(value.split()[0])
    return out


def accessible_kb(pid):
    """The size of every mapping the process may touch (any of r, w, x), from
    /proc/<pid>/maps: what `mlockall(MCL_CURRENT | MCL_FUTURE)` would make resident. The
    reservations with no access (stack guards, the allocator's arena reservations) are
    left out; `VmSize` counts them."""
    total = 0
    for line in open(f"/proc/{pid}/maps"):
        span, perms = line.split()[:2]
        if perms[:3] != "---":
            lo, hi = span.split("-")
            total += int(hi, 16) - int(lo, 16)
    return total // 1024


def sample(pid, roles):
    s = {"mono_ns": time.monotonic_ns(), "loadavg": open("/proc/loadavg").read().split()[:3]}
    s["process_ticks"] = stat_ticks(f"/proc/{pid}/stat")
    threads = {}
    for tid in os.listdir(f"/proc/{pid}/task"):
        base = f"/proc/{pid}/task/{tid}"
        try:
            run_ns = int(open(f"{base}/schedstat").read().split()[0])
            threads[tid] = {"role": roles.get(tid, "unlisted"), "ticks": stat_ticks(f"{base}/stat"), "run_ns": run_ns}
        except (FileNotFoundError, ProcessLookupError):
            pass
    s["threads"] = threads
    s["status"] = kb_fields(f"/proc/{pid}/status", {"VmRSS", "RssAnon", "RssFile", "VmHWM", "VmSize", "VmData", "VmLck", "Threads"})
    s["status"]["AccessibleKb"] = accessible_kb(pid)
    s["smaps_rollup"] = kb_fields(f"/proc/{pid}/smaps_rollup", {"Rss", "Pss", "Pss_Anon"})
    return s


def roles_of(server_log):
    """tid -> role, from the scheduling report the server prints at start."""
    roles = {}
    for line in open(server_log, errors="replace"):
        m = re.search(r"thread role=(\S+) tid=(\d+)", line)
        if m:
            roles[m.group(2)] = m.group(1)
    return roles


def group_of(role):
    if role.startswith("player-"):
        return "players"
    if role.startswith("upnp-"):
        return "upnp"
    if role == "audio":
        return "audio"
    if role.startswith("client"):
        return "clients"
    return "other"


# --- the control point ------------------------------------------------------------------


def http_once(address, method, path, headers=None, body=None, timeout=10):
    host, port = address.rsplit(":", 1)
    c = http.client.HTTPConnection(host, int(port), timeout=timeout)
    c.request(method, path, body=body, headers=headers or {})
    r = c.getresponse()
    data = r.read().decode(errors="replace")
    c.close()
    return r.status, dict((k.lower(), v) for k, v in r.getheaders()), data


def discover(ssdp_port):
    """Every renderer: one search for the device type, then each LOCATION's description."""
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.bind(("127.0.0.1", 0))
    sock.settimeout(0.2)
    sock.sendto(
        f'M-SEARCH * HTTP/1.1\r\nHOST: {SSDP_HOST}\r\nMAN: "ssdp:discover"\r\nMX: 1\r\nST: {DEVICE}\r\n\r\n'.encode(),
        ("127.0.0.1", ssdp_port),
    )
    locations = set()
    until = time.monotonic() + 2.5
    while time.monotonic() < until:
        try:
            data, _ = sock.recvfrom(4096)
        except socket.timeout:
            continue
        m = re.search(r"(?im)^LOCATION:\s*(\S+)", data.decode(errors="replace"))
        if m:
            locations.add(m.group(1))
    devices = []
    for location in sorted(locations):
        m = re.match(r"http://([^/]+)(/.*)$", location)
        status, _, text = http_once(m.group(1), "GET", m.group(2))
        if status != 200:
            continue
        device = {"address": m.group(1), "name": re.search(r"<friendlyName>([^<]*)<", text).group(1), "services": {}}
        for block in re.findall(r"<service>(.*?)</service>", text, re.S):
            kind = re.search(r"<serviceType>([^<]*)<", block).group(1)
            device["services"][kind] = {
                "control": re.search(r"<controlURL>([^<]*)<", block).group(1),
                "event": re.search(r"<eventSubURL>([^<]*)<", block).group(1),
            }
        devices.append(device)
    return devices


def soap(device, action, arguments):
    body = (
        '<?xml version="1.0"?>\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" '
        's:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body>'
        f'<u:{action} xmlns:u="{AVT}">'
        + "".join(f"<{k}>{escape(v)}</{k}>" for k, v in arguments)
        + f"</u:{action}></s:Body></s:Envelope>"
    )
    status, _, text = http_once(
        device["address"], "POST", device["services"][AVT]["control"],
        {"Content-Type": 'text/xml; charset="utf-8"', "SOAPACTION": f'"{AVT}#{action}"', "Connection": "close"},
        body.encode(),
    )
    return status, text


def must(device, action, arguments):
    status, text = soap(device, action, arguments)
    if status != 200:
        die(f"{action} on {device['name']} was answered {status}: {text[:400]}")
    return text


def value(text, name):
    m = re.search(rf"<{name}>([^<]*)</{name}>", text)
    return m.group(1) if m else ""


def transport_state(device):
    return value(must(device, "GetTransportInfo", [("InstanceID", "0")]), "CurrentTransportState")


def position_s(device):
    rel = value(must(device, "GetPositionInfo", [("InstanceID", "0")]), "RelTime")
    parts = rel.split(":")
    if len(parts) != 3:
        return -1.0
    return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])


def wait_for(what, done, limit_s=60):
    until = time.monotonic() + limit_s
    while time.monotonic() < until:
        if done():
            return
        time.sleep(0.2)
    die(f"{what}: not within {limit_s} s")


class Callback(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    count = 0

    def log_message(self, *_):
        pass

    def do_NOTIFY(self):
        self.rfile.read(int(self.headers.get("Content-Length", "0")))
        Callback.count += 1
        self.send_response(200)
        self.send_header("Content-Length", "0")
        self.send_header("Connection", "close")
        self.end_headers()
        self.close_connection = True


def subscribe_all(devices):
    server = Threaded(("127.0.0.1", 0), Callback)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    port = server.server_address[1]
    made = 0
    for d in devices:
        for kind, service in sorted(d["services"].items()):
            status, _, text = http_once(
                d["address"], "SUBSCRIBE", service["event"],
                {"HOST": d["address"], "CALLBACK": f"<http://127.0.0.1:{port}/{made}>", "NT": "upnp:event",
                 "TIMEOUT": "Second-1800"},
            )
            if status != 200:
                die(f"SUBSCRIBE {kind} on {d['name']} was answered {status}: {text[:200]}")
            made += 1
    return made


def command(control, body):
    status, _, text = http_once(control, "POST", "/api/command",
                                {"Host": "chorus", "Content-Type": "application/json"}, body.encode())
    if status != 200:
        die(f"the control plane answered {status} to {body}: {text[:300]}")


def window(pid, roles, seconds, between_s=10):
    """Both ends of one window, and the resident set every `between_s` inside it."""
    start = sample(pid, roles)
    rss = []
    until = time.monotonic() + seconds
    while True:
        left = until - time.monotonic()
        if left <= 0:
            break
        time.sleep(min(between_s, left))
        rss.append(kb_fields(f"/proc/{pid}/status", {"VmRSS"}).get("VmRSS", 0))
    return start, sample(pid, roles), rss


def reduce_window(start, end, rss, extra):
    wall_ns = end["mono_ns"] - start["mono_ns"]
    tick_hz = os.sysconf("SC_CLK_TCK")
    groups, per_player = {}, {}
    for tid, e in end["threads"].items():
        s = start["threads"].get(tid)
        if s is None:
            continue
        g = group_of(e["role"])
        acc = groups.setdefault(g, {"ticks": 0, "run_ns": 0, "threads": 0})
        acc["ticks"] += e["ticks"] - s["ticks"]
        acc["run_ns"] += e["run_ns"] - s["run_ns"]
        acc["threads"] += 1
        if g == "players":
            per_player[e["role"]] = {"ticks": e["ticks"] - s["ticks"], "run_ns": e["run_ns"] - s["run_ns"]}
    pct = lambda ns: round(100.0 * ns / wall_ns, 4)  # noqa: E731
    row = dict(extra)
    row.update({
        "wall_s": round(wall_ns / 1e9, 3),
        "tick_hz": tick_hz,
        "process_ticks": end["process_ticks"] - start["process_ticks"],
        "process_pct_ticks": round(100.0 * (end["process_ticks"] - start["process_ticks"]) / tick_hz / (wall_ns / 1e9), 4),
        "process_pct": pct(sum(g["run_ns"] for g in groups.values())),
        "groups": {name: {"threads": g["threads"], "ticks": g["ticks"], "pct": pct(g["run_ns"])}
                   for name, g in sorted(groups.items())},
        "players": {role: {"ticks": p["ticks"], "pct": pct(p["run_ns"])} for role, p in sorted(per_player.items())},
        "status_start": start["status"], "status_end": end["status"],
        "smaps_start": start["smaps_rollup"], "smaps_end": end["smaps_rollup"],
        "rss_kb_max_in_window": max(rss + [end["status"].get("VmRSS", 0)]),
        "loadavg_start": start["loadavg"], "loadavg_end": end["loadavg"],
    })
    return row


def measure(args):
    pid = args.pid
    roles = roles_of(args.server_log)
    if not roles:
        die(f"{args.server_log} holds no `thread role=` line; the server's scheduling report is how threads are told apart")
    os.makedirs(args.out, exist_ok=True)
    raw = open(os.path.join(args.out, "samples.jsonl"), "a")
    rows = open(os.path.join(args.out, "windows.jsonl"), "a")

    def record(label, k, start, end, rss, extra=None):
        base = {"label": label, "format": args.format, "k": k, "config": args.config}
        base.update(extra or {})
        raw.write(json.dumps({"label": label, "k": k, "at": "start", **start}) + "\n")
        raw.write(json.dumps({"label": label, "k": k, "at": "end", **end}) + "\n")
        row = reduce_window(start, end, rss, base)
        rows.write(json.dumps(row) + "\n")
        raw.flush()
        rows.flush()
        if args.control:
            _, _, text = http_once(args.control, "GET", "/api/report", {"Host": "chorus"})
            with open(os.path.join(args.out, f"report-{args.format}-{label}-k{k}.txt"), "w") as f:
                f.write(text)
        g = row["groups"]
        print(f"window {label} k={k}: process {row['process_pct']:.3f} % of one core, "
              + ", ".join(f"{n} {v['pct']:.3f}" for n, v in g.items())
              + f"; VmRSS {row['status_end'].get('VmRSS')} kB, load {row['loadavg_start'][0]} to {row['loadavg_end'][0]}",
              flush=True)

    if args.idle_bare:
        # No control point at all: nothing is searched, described or subscribed.
        start, end, rss = window(pid, roles, args.window)
        record("idle-no-control-point", 0, start, end, rss)
        if not args.subscribe and not args.ks:
            return

    devices = []
    if args.ssdp_port:
        wait_for("the renderers answer a search", lambda: len(discover(args.ssdp_port)) >= args.renderers, 30)
        devices = sorted(discover(args.ssdp_port), key=lambda d: d["name"])
        if len(devices) != args.renderers:
            die(f"{len(devices)} renderers answered, {args.renderers} expected")
    if args.subscribe:
        made = subscribe_all(devices)
        time.sleep(args.settle)
        start, end, rss = window(pid, roles, args.window)
        record("idle-one-subscribed-control-point", 0, start, end, rss,
               {"subscriptions": made, "events_received": Callback.count})
    ks = [int(k) for k in args.ks.split(",") if k]
    if not ks:
        return
    for room in args.rooms.split(","):
        command(args.control, json.dumps({"v": 2, "t": "take", "target": room, "source": "none"}))
    time.sleep(args.settle)
    start, end, rss = window(pid, roles, args.window)
    record("idle", 0, start, end, rss)
    name, ext, mime, _ = next(e for e in ENCODES if e[0] == args.format)
    for k in ks:
        playing = devices[:k]
        for i, d in enumerate(playing):
            # A query makes each stream its own URL, as K different tracks would be.
            url = f"http://127.0.0.1:{args.media_port}/{name}.{ext}?stream={i}"
            must(d, "SetAVTransportURI", [("InstanceID", "0"), ("CurrentURI", url), ("CurrentURIMetaData", "")])
            must(d, "Play", [("InstanceID", "0"), ("Speed", "1")])
        wait_for(f"{k} renderers PLAYING", lambda: all(transport_state(d) == "PLAYING" for d in playing))
        time.sleep(args.settle)
        before = [position_s(d) for d in playing]
        start, end, rss = window(pid, roles, args.window)
        after = [position_s(d) for d in playing]
        states = [transport_state(d) for d in playing]
        advanced = [round(b - a, 1) for a, b in zip(before, after)]
        ok = all(s == "PLAYING" for s in states) and all(abs(x - args.window) <= 3 for x in advanced)
        record("playing", k, start, end, rss,
               {"position_advance_s": advanced, "states_end": sorted(set(states)), "steady": ok})
        if not ok:
            print(f"NOT STEADY k={k}: states {states}, positions advanced {advanced} in a {args.window} s window", flush=True)
        for d in playing:
            must(d, "Stop", [("InstanceID", "0")])
        wait_for("every renderer STOPPED", lambda: all(transport_state(d) == "STOPPED" for d in playing))
        time.sleep(3)


# --- the decoders alone ----------------------------------------------------------------------


def probe(args):
    """`chorus-server --probe-media` on each file: the decoder alone (no fetch, no
    resampler, no stream), as CPU seconds of the child process per second of audio."""
    os.makedirs(args.out, exist_ok=True)
    seconds = {}
    with open(os.path.join(args.out, "probe-media.tsv"), "a") as f:
        f.write("format\trun\tcpu_s\twall_s\taudio_s\tpct_of_one_core\tmaxrss_kb\tloadavg\tline\n")
        for name, ext, _, _ in ENCODES:
            path = os.path.join(args.dir, f"{name}.{ext}")
            for run in range(args.runs):
                t0 = time.monotonic()
                child = subprocess.Popen([args.server, "--probe-media", path], stdout=subprocess.PIPE, text=True)
                said = child.stdout.read()
                _, status, usage = os.wait4(child.pid, 0)
                child.returncode = status
                wall = time.monotonic() - t0
                if status != 0:
                    die(f"--probe-media {path} ended with wait status {status}")
                line = said.strip().splitlines()[-1]
                rate = int(re.search(r"rate=(\d+)", line).group(1))
                frames = int(re.search(r"frames=(\d+)", line).group(1))
                audio = frames / rate
                seconds[name] = audio
                cpu = usage.ru_utime + usage.ru_stime
                f.write(f"{name}\t{run}\t{cpu:.3f}\t{wall:.3f}\t{audio:.2f}\t{100 * cpu / audio:.4f}\t"
                        f"{usage.ru_maxrss}\t{open('/proc/loadavg').read().split()[0]}\t{line}\n")
                f.flush()
                print(f"probe-media {name} run {run}: {cpu:.3f} CPU s for {audio:.1f} s of audio, "
                      f"{100 * cpu / audio:.3f} % of one core", flush=True)


# --- the report's tables --------------------------------------------------------------------


def summary(args):
    """The report's tables, from the `windows.jsonl` (and `probe-media.tsv`) of one or more
    run directories. CPU is the scheduler's run time over the window, as % of one core."""
    rows, probes = [], []
    for path in args.windows:
        if path.endswith(".tsv"):
            lines = [line.rstrip("\n").split("\t") for line in open(path)]
            probes += [dict(zip(lines[0], line)) for line in lines[1:] if line[0] != "format"]
        else:
            rows += [json.loads(line) for line in open(path)]
    g = lambda r, n: r["groups"].get(n, {"pct": 0.0})["pct"]  # noqa: E731
    order = [e[0] for e in ENCODES]
    formats = [f for f in order if any(r["format"] == f for r in rows)]
    by = {(r["format"], r["k"]): r for r in rows if r["label"] in ("idle", "playing")}
    ks = sorted({k for (_, k) in by if k})
    cell = lambda f, k, fn: fn(by[(f, k)]) if (f, k) in by else "-"  # noqa: E731

    if probes:
        print("Decoders alone (`--probe-media`), CPU seconds per second of audio as % of one core:\n")
        print("| format | runs | median | lowest | highest |")
        print("|---|---|---|---|---|")
        for f in order:
            mine = sorted(float(p["pct_of_one_core"]) for p in probes if p["format"] == f)
            if mine:
                print(f"| {f} | {len(mine)} | {mine[len(mine) // 2]:.3f} | {mine[0]:.3f} | {mine[-1]:.3f} |")
        print()
    if formats:
        head = "| format | " + " | ".join(f"K = {k}" for k in ks) + " |"
        rule = "|---|" + "---|" * len(ks)
        print("Player threads, % of one core per playing stream (the mean of the K busiest player threads):\n")
        print(head + "\n" + rule)

        def per_stream(r):
            busy = sorted(p["pct"] for p in r["players"].values())[-r["k"]:]
            return f"{sum(busy) / r['k']:.2f}"

        for f in formats:
            print(f"| {f} | " + " | ".join(cell(f, k, per_stream) for k in ks) + " |")
        print("\nThe idlest and the busiest of those K threads in each window, % of one core:\n")
        print(head + "\n" + rule)
        for f in formats:
            def spread(r):
                busy = sorted(p["pct"] for p in r["players"].values())[-r["k"]:]
                return f"{busy[0]:.2f} to {busy[-1]:.2f}"
            print(f"| {f} | " + " | ".join(cell(f, k, spread) for k in ks) + " |")
        ks0 = [0] + ks
        head0 = "| format | " + " | ".join(f"K = {k}" for k in ks0) + " |"
        rule0 = "|---|" + "---|" * len(ks0)
        for title, fn in (
            ("The audio thread, % of one core", lambda r: f"{g(r, 'audio'):.2f}"),
            ("The client threads (two per endpoint slot, 16 endpoints connected), % of one core, sum",
             lambda r: f"{g(r, 'clients'):.2f}"),
            ("The renderers' threads (`upnp-*`), % of one core, sum", lambda r: f"{g(r, 'upnp'):.2f}"),
            ("Every other thread, % of one core, sum", lambda r: f"{g(r, 'other'):.2f}"),
            ("The whole process, % of one core", lambda r: f"{r['process_pct']:.2f}"),
            ("The whole process by clock ticks (utime + stime), % of one core", lambda r: f"{r['process_pct_ticks']:.2f}"),
            ("VmRSS at the window's end, kB", lambda r: str(r["status_end"].get("VmRSS"))),
            ("RssAnon at the window's end, kB", lambda r: str(r["status_end"].get("RssAnon"))),
            ("Pss (smaps_rollup) at the window's end, kB", lambda r: str(r["smaps_end"].get("Pss"))),
            ("VmHWM at the window's end, kB", lambda r: str(r["status_end"].get("VmHWM"))),
            ("VmSize at the window's end, kB", lambda r: str(r["status_end"].get("VmSize"))),
            ("Mapped with any access (what locking memory would make resident), kB",
             lambda r: str(r["status_end"].get("AccessibleKb", "-"))),
            ("Threads", lambda r: str(r["status_end"].get("Threads"))),
            ("Load average (1 min) at the window's start and end", lambda r: f"{r['loadavg_start'][0]} to {r['loadavg_end'][0]}"),
            ("Steady (every renderer PLAYING at the end and its position advanced by the window, within 3 s)",
             lambda r: "yes" if r.get("steady", True) else "NO"),
        ):
            print(f"\n{title}:\n")
            print(head0 + "\n" + rule0)
            for f in formats:
                print(f"| {f} | " + " | ".join(cell(f, k, fn) for k in ks0) + " |")
        print("\nRssAnon growth per playing stream against the same server's K = 0, kB:\n")
        print(head + "\n" + rule)
        for f in formats:
            base = by[(f, 0)]["status_end"].get("RssAnon", 0) if (f, 0) in by else 0
            print(f"| {f} | " + " | ".join(
                cell(f, k, lambda r: f"{(r['status_end'].get('RssAnon', 0) - base) / r['k']:.0f}") for k in ks) + " |")
        print()
    idle = [r for r in rows if r["label"].startswith("idle-")]
    if idle:
        print("Idle servers, no endpoint connected (% of one core; kB):\n")
        print("| configuration | window | threads | upnp threads | player threads | audio | process | VmRSS | RssAnon | Pss | "
              "Pss_Anon | VmSize | mapped with any access | load 1 min |")
        print("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for r in idle:
            st, sm = r["status_end"], r["smaps_end"]
            print(f"| {r['config']} | {r['label']} | {st.get('Threads')} | {g(r, 'upnp'):.3f} | {g(r, 'players'):.3f} | "
                  f"{g(r, 'audio'):.3f} | {r['process_pct']:.3f} | {st.get('VmRSS')} | {st.get('RssAnon')} | {sm.get('Pss')} | "
                  f"{sm.get('Pss_Anon')} | {st.get('VmSize')} | {st.get('AccessibleKb', '-')} | {r['loadavg_start'][0]} to {r['loadavg_end'][0]} |")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="mode", required=True)
    m = sub.add_parser("media")
    m.add_argument("--prefix", required=True)
    m.add_argument("--out", required=True)
    m.add_argument("--seconds", type=int, default=SECONDS_DEFAULT)
    s = sub.add_parser("serve")
    s.add_argument("--dir", required=True)
    s.add_argument("--port-file", required=True)
    x = sub.add_parser("measure")
    x.add_argument("--pid", type=int, required=True)
    x.add_argument("--server-log", required=True)
    x.add_argument("--out", required=True)
    x.add_argument("--config", required=True, help="what the report calls this server configuration")
    x.add_argument("--format", default="-")
    x.add_argument("--ks", default="")
    x.add_argument("--window", type=float, default=60)
    x.add_argument("--settle", type=float, default=10)
    x.add_argument("--ssdp-port", type=int, default=0)
    x.add_argument("--renderers", type=int, default=0)
    x.add_argument("--control", default="")
    x.add_argument("--rooms", default="")
    x.add_argument("--media-port", type=int, default=0)
    x.add_argument("--idle-bare", action="store_true")
    x.add_argument("--subscribe", action="store_true")
    p = sub.add_parser("probe")
    p.add_argument("--server", required=True)
    p.add_argument("--dir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--runs", type=int, default=3)
    y = sub.add_parser("summary")
    y.add_argument("windows", nargs="+")
    args = ap.parse_args()
    {"media": make_media, "serve": serve, "measure": measure, "probe": probe, "summary": summary}[args.mode](args)


if __name__ == "__main__":
    main()
