#!/usr/bin/env bash
# The bench scripts' report-and-PR path, end to end, on fixture captures (K45).
#
# For EVERY hardware entry point in tools/bench/topics.conf: a run directory is
# built from committed fixtures (the chirp-pair captures and offsets series in
# fixtures/measure/, the client and server output of the device-class runs in
# fixtures/bench/, and delay logs and client output generated here in their
# formats),
# the entry point is driven with `--report-from` in a throwaway clone of this
# checkout whose `origin` is a local bare repository, with CHORUS_BENCH_PR=1 and
# a fake gh that records its arguments, and this asserts:
#   - the report file exists and validates (tools/bench/validate-report.sh)
#   - every raw file's sha256 in the report matches the run's file
#   - the branch bench/<date>-<topic> was pushed to the bare remote, carrying
#     the report, and the clone is back on a clean main (each case runs from
#     where the previous one left it, as the scripts of `make verify-device` do)
#   - the fake gh saw `pr create --base main --head bench/<date>-<topic>`
# and then that tools/bench/validate-open-prs.sh finds every one of those PRs
# valid, that the validator refuses a raw file equal to a fixture without the
# test-only flag, that the report half refuses a dirty tree and an unpushed
# commit, and that a FAIL run exits 1 with its report written and PR opened.
# The measure half is not run: it needs hardware and keeps refusing without it (tools/unrun-checks-are-visibly-unrun.sh). No device, no network,
# no real gh. Prints one line per entry point.
#
#   bash tools/bench/e2e-test.sh
set -euo pipefail

source "$(dirname "$0")/../lib.sh"
build_once

FIX="$REPO_ROOT/fixtures/measure"
DATE="2026-10-01"
T="$(mktemp -d "${TMPDIR:-/tmp}/chorus-bench-e2e-XXXXXX")"
# CHORUS_BENCH_E2E_KEEP=1 keeps the clone, the remote and the runs for a look.
[ "${CHORUS_BENCH_E2E_KEEP:-0}" = 1 ] || trap 'rm -rf "$T"' EXIT
FAILURES=0
fail() { printf 'FAIL %s\n' "$*"; FAILURES=$((FAILURES + 1)); }

# --- a clone of this checkout with a bare remote ---------------------------------
# The clone carries the files the report half reads (tools, config, fixtures,
# the measurements directory), as they are in this working tree, committed once
# and pushed to the bare remote as its main.
export GIT_AUTHOR_NAME="chorus bench test" GIT_AUTHOR_EMAIL="bench-test@example.invalid"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
CLONE="$T/clone"
REMOTE="$T/remote.git"
mkdir -p "$CLONE"
git init -q --bare -b main "$REMOTE"
(cd "$REPO_ROOT" && git ls-files -c -o --exclude-standard -- tools config fixtures docs/measurements \
    | while IFS= read -r f; do [ -f "$f" ] && printf '%s\0' "$f"; done \
    | tar --null -T - -cf -) | tar -C "$CLONE" -xf -
git -C "$CLONE" init -q -b main
git -C "$CLONE" add -A
git -C "$CLONE" commit -q -m "bench e2e: snapshot of the checkout under test"
git -C "$CLONE" remote add origin "$REMOTE"
git -C "$CLONE" push -q -u origin main
HEAD_SHA="$(git -C "$CLONE" rev-parse HEAD)"

# --- a fake gh -------------------------------------------------------------------
GH_LOG="$T/gh-calls.log"
: > "$GH_LOG"
cat > "$T/fake-gh" <<EOF
#!/usr/bin/env bash
# Records every call; answers 'pr create' with a URL and 'pr list' with the PRs
# created so far, as "<n> <head>" lines (what --jq would print).
printf '%s\n' "\$*" >> "$GH_LOG"
# Keep each PR body, so the test can read what the owner's PR would say.
body=""; prev=""
for a in "\$@"; do [ "\$prev" = "--body-file" ] && body="\$a"; prev="\$a"; done
[ -n "\$body" ] && cp "\$body" "$T/pr-body-\$(grep -c '^pr create' "$GH_LOG").md"
case "\$1 \$2" in
    "pr create")
        n=\$(grep -c '^pr create' "$GH_LOG")
        echo "https://github.invalid/chorus/pull/\$n" ;;
    "pr list")
        grep '^pr create' "$GH_LOG" | sed -n 's/.*--head \([^ ]*\).*/\1/p' | awk '{ print NR, \$1 }' ;;
esac
EOF
chmod +x "$T/fake-gh"

# --- delay logs in the chorus delay log v1 format ---------------------------------
# <file> <seconds> [interval_us]: samples every interval (default 500 ms) for
# the whole run, all graded, delay held at the target, a clean summary.
delay_log() {
    local file="$1" seconds="$2" interval="${3:-500000}"
    awk -v s="$seconds" -v step="$interval" 'BEGIN {
        print "# chorus delay log v1"
        print "# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT"
        print "config min_us=60000 max_us=300000 start_fill_us=120000 device_target_us=120000 device=fixture rate_hz=48000 channels=2 sample_format=pcm_s16le frames_per_chunk=960 overflow_skew_ppm=2000"
        n = int(s * 1000000 / step)
        for (i = 0; i <= n; i++) printf "sample mono_us=%d delay_us=120000 occupancy_us=140000 graded=1\n", i * step
        span = n * step
        frames = int(span / 1000000 * 48000)
        printf "summary graded_span_us=%d graded_samples=%d delay_min_us=120000 delay_max_us=120000 margin_to_min_us=60000 margin_to_max_us=180000 underruns=0 discarded_overflow=0 discarded_late=0 discarded_duplicate=0 discarded_malformed=0 frames_written=%d frames_played=%d nominal_frames=%d\n", span, n + 1, frames, frames, frames
    }' > "$file"
}

# The owner runs the rig scripts with the second endpoint as an ssh target and
# may name the server host; neither may reach a report or a PR body (K27).
export CHORUS_SECOND_ENDPOINT="owner@endpoint-b.example" CHORUS_SERVER_HOST="bench-host.example"

# A run directory as the measure half leaves one.
new_run() {
    local topic="$1"
    RUN="$T/runs/$topic"
    mkdir -p "$RUN/raw"
    {
        printf 'topic = %s\n' "$topic"
        printf 'entry_point = %s\n' "$(awk -F'|' -v t="$topic" '{ k = $1; gsub(/ /, "", k) } k == t { v = $2; gsub(/ /, "", v); print v }' "$REPO_ROOT/tools/bench/topics.conf")"
        printf 'date = %s\n' "$DATE"
        printf 'build = %s\n' "$HEAD_SHA"
        printf 'criterion = the fixture-driven test of the report and PR path\n'
        printf 'device = fixture capture from fixtures/measure (NOT A MEASUREMENT)\n'
        # What a careless device note would carry: the scrub has to take it out.
        printf 'device = second endpoint %s, served from %s\n' "$CHORUS_SECOND_ENDPOINT" "$CHORUS_SERVER_HOST"
    } > "$RUN/bench-run.conf"
}

new_run rig3-capture
cp "$FIX/01-chirp-pair-a.wav" "$RUN/raw/capture.wav"

new_run rig3-free-run
cp "$FIX/16-free-run-client-a.offsets" "$RUN/raw/client-a.offsets"
cp "$FIX/17-free-run-client-b.offsets" "$RUN/raw/client-b.offsets"

new_run sync4-hour
cp "$FIX/01-chirp-pair-a.wav" "$RUN/raw/capture-1.wav"
cp "$FIX/02-chirp-pair-b.wav" "$RUN/raw/capture-2.wav"
cp "$FIX/03-chirp-pair-exchanged.wav" "$RUN/raw/capture-3.wav"
delay_log "$RUN/raw/sync-hour-endpoint-a.log" 3700
delay_log "$RUN/raw/sync-hour-endpoint-b.log" 3700

new_run embedded5-endpoint-rig
cp "$FIX/01-chirp-pair-a.wav" "$RUN/raw/capture-1.wav"
cp "$FIX/02-chirp-pair-b.wav" "$RUN/raw/capture-2.wav"
# 1.5 s with channel L 150 ppm fast: the one capture long enough for the
# produced rate (AC-3, `chorus-measure rate`) to resolve, inside the servo's
# correction authority, so the run is a PASS.
cp "$FIX/18-rate-skewed.wav" "$RUN/raw/capture-3.wav"
delay_log "$RUN/raw/endpoint-rig-linux.log" 3700

new_run wifi7-wireless
cp "$FIX/01-chirp-pair-a.wav" "$RUN/raw/capture-none.wav"
cp "$FIX/02-chirp-pair-b.wav" "$RUN/raw/capture-min-modem.wav"
cp "$FIX/14-wireless-jitter-ps-none.offsets" "$RUN/raw/wireless-none.offsets"
cp "$FIX/15-wireless-jitter-ps-min-modem.offsets" "$RUN/raw/wireless-min-modem.offsets"

# Three days at one sample a second: larger than the committed limit, so this
# one exercises the hashed-only, kept-on-the-owner's-machine path.
new_run product6-soak
delay_log "$RUN/raw/local.log" 259200 1000000
delay_log "$RUN/raw/remote.log" 600

new_run sound2-ten-minute
delay_log "$RUN/raw/ten-minute-run.log" 620

# The device-class runs of `make verify-device` and the device-loss run. Their
# fixtures are the real binaries' output from a run on the ALSA `null` device
# (fixtures/bench/README.md), which is enough for what these graders read.
BFIX="$REPO_ROOT/fixtures/bench"
new_run sound2-stream-end-and-loss
cp "$BFIX"/stream-end-and-loss/* "$RUN/raw/"
printf 'clean_end_client_exit = 0\nlost_server_client_exit = 3\n' > "$RUN/raw/run-status.txt"

new_run sound2-start-fill
cp "$BFIX/start-fill-and-log-shape.log" "$RUN/raw/start-fill-and-log-shape.log"
printf 'client_exit = 0\n' > "$RUN/raw/run-status.txt"

# A pacing device's minute: the null capture cannot stand in (its delay is
# zero), so the log is generated, with the start-fill event a real run writes.
new_run sound2-delay-log-shape
delay_log "$RUN/raw/delay-log-shape.log" 62
sed -i '/^config /a event mono_us=0 kind=start-fill start_fill_us=120000 filled_us=120000 filled_frames=5760' "$RUN/raw/delay-log-shape.log"
printf 'client_exit = 0\n' > "$RUN/raw/run-status.txt"

# The over-rate run: a crossing at the maximum, chunks discarded at the ceiling.
new_run sound2-overflow
delay_log "$RUN/raw/overflow-run.log" 270
sed -i '/^config /a event mono_us=120000000 kind=bound-crossing bound=maximum occupancy_us=300000 max_us=300000 discarded_overflow=1' "$RUN/raw/overflow-run.log"
printf 'chorus-client: stopped reason=run-length-reached played=1 underruns=0 discarded_overflow=412 (generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT)\n' \
    > "$RUN/raw/client.stdout"
{
    printf 'client_exit = 0\nskew_ppm = 2000\n'
    printf 'config_sha256_before = %s\nconfig_sha256_after = %s\n' "$(printf a | sha256sum | cut -d' ' -f1)" "$(printf a | sha256sum | cut -d' ' -f1)"
} > "$RUN/raw/run-status.txt"

# A device removed mid-run: the client names it and the reason, and exits 3.
new_run sound2-device-loss
delay_log "$RUN/raw/delay.log" 5
{
    printf '# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT\n'
    printf 'chorus-client: stopped reason=delay-refused played=1 delay_log=<run>/raw/delay.log\n'
    printf 'chorus-client: the audio device hw:9,0 refused its delay query: No such device\n'
} > "$RUN/raw/client.out"
printf 'client_exit = 3\ndevice = hw:9,0\n' > "$RUN/raw/run-status.txt"

# The endpoint console's decode-cost reply (firmware/src/console.c's format),
# written here: NOT A MEASUREMENT.
new_run embedded5-decode-cost
{
    printf '# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT\n'
    printf 'decode-cost flac-s16-stereo-44k1:codec=flac,rate=44100,channels=2,frames=44877,elapsed_us=120000,frames_per_s=373975,cpu_fraction=0.1179,decode_matches=yes'
    printf ' opus-tv10-celt-stereo:codec=opus,rate=48000,channels=2,frames=49320,elapsed_us=410000,frames_per_s=120293,cpu_fraction=0.3990,decode_matches=yes stack_free_bytes=5120\n'
} > "$RUN/raw/console.txt"

# The EMBEDDED-5 bring-up's console replies (firmware/src/console.c's formats),
# written here: NOT A MEASUREMENT.
new_run embedded5-bringup
STATUS_WORDS='link=up transport=wired wifi=not-applicable wifi_ps_declared=not-applicable wifi_ps_in_force=not-applicable wireless_bound=not-applicable rejoins=0 attempts=1'
printf '# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT\nstatus chorus-endpoint: link=down transport=wired audio=idle chunks=0 amp=ok amp_fault_bits=0x00\n' > "$RUN/raw/status-before.txt"
printf '# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT\nstatus chorus-endpoint: %s audio=running chunks=500 frames=480000 amp=ok amp_fault_bits=0x00 played=470000 underrun_frames=0 late_chunks=0 correction_ppm=3.100 sync_error_ns=4200\n' "$STATUS_WORDS" > "$RUN/raw/status-playing.txt"
printf '# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT\nstatus chorus-endpoint: %s audio=running chunks=9000 frames=8640000 amp=ok amp_fault_bits=0x00 sync_error_ns=3900\n' "$STATUS_WORDS" > "$RUN/raw/status-end.txt"
RES='heap_internal_free=61234 heap_internal_min_free=52000 heap_psram_free=none heap_psram_min_free=none stack_free.chorus-playout=1800 stack_free.chorus-session=9000 stack_free.console_repl=5100 stack_free.wifi=absent fifo_frames=1150.2 fifo_us=23962.5 marker_pin=none'
for phase in before playing end; do
    printf '# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT\nresources %s\n' "$RES" > "$RUN/raw/resources-$phase.txt"
done
{
    printf '# generated by tools/bench/e2e-test.sh: NOT A MEASUREMENT\n'
    for round in 1 2 3; do
        printf 'cycle %d outage_s=%d bound_s=15 recovered=yes after_s=4 status: status chorus-endpoint: audio=running chunks=%d\n' "$round" "$round" "$((1000 * round))"
    done
} > "$RUN/raw/cycles.txt"

# --- drive every entry point's report and PR half --------------------------------
# name | topic | the result word the fixtures lead to
CASES="capture-run|rig3-capture|MEASURED
free-run-run|rig3-free-run|MEASURED
sync-hour-run|sync4-hour|PASS
endpoint-rig-run|embedded5-endpoint-rig|PASS
decode-cost-run|embedded5-decode-cost|MEASURED
embedded5-bringup-run|embedded5-bringup|PASS
wireless-characterization-run|wifi7-wireless|PASS
soak-run|product6-soak|INCOMPLETE
ten-minute-run|sound2-ten-minute|PASS
stream-end-and-loss|sound2-stream-end-and-loss|PASS
start-fill-and-log-shape|sound2-start-fill|PASS
delay-log-shape|sound2-delay-log-shape|PASS
overflow-run|sound2-overflow|PASS
device-loss-run|sound2-device-loss|PASS"

# Every topic is covered: the list above and topics.conf name the same set.
TOPICS_CONF="$(awk -F'|' '/^[[:space:]]*#/ || NF < 3 { next } { k = $1; gsub(/ /, "", k); print k }' "$REPO_ROOT/tools/bench/topics.conf" | sort)"
TOPICS_HERE="$(printf '%s\n' "$CASES" | cut -d'|' -f2 | sort)"
[ "$TOPICS_CONF" = "$TOPICS_HERE" ] || fail "the cases here and tools/bench/topics.conf differ: $(printf '%s' "$TOPICS_CONF" | tr '\n' ' ') vs $(printf '%s' "$TOPICS_HERE" | tr '\n' ' ')"

bench_env() {
    env CHORUS_SKIP_BUILD=1 CARGO_TARGET_DIR="$TARGET_DIR" CHORUS_BENCH_PR=1 \
        CHORUS_BENCH_GH="$T/fake-gh" CHORUS_BENCH_ALLOW_FIXTURE_RAW=1 "$@"
}

while IFS='|' read -r name topic want; do
    entry="$(awk -F'|' -v t="$topic" '{ k = $1; gsub(/ /, "", k) } k == t { v = $2; gsub(/ /, "", v); print v }' "$REPO_ROOT/tools/bench/topics.conf")"
    branch="bench/$DATE-$topic"
    rel="docs/measurements/$topic-$DATE.md"
    log="$T/$name.log"
    # No switch back to main here: each run has to leave the clone there
    # itself, as the next script of a bench session relies on (checked below).
    set +e
    (cd "$CLONE" && bench_env bash "$entry" --report-from "$T/runs/$topic") > "$log" 2>&1
    rc=$?
    set -e
    report_ok=1
    pr_ok=1
    result="$( (git -C "$REMOTE" show "$branch:$rel" 2>/dev/null || true) | sed -n 's/^Result: \([A-Z]*\):.*/\1/p')"
    if [ "$result" != "$want" ]; then
        fail "$name: the report's result is '${result:-<none>}', the fixtures lead to $want (exit $rc; tail below)"
        tail -n 15 "$log" | sed 's/^/    /'
        report_ok=0
    fi
    case "$want" in PASS | MEASURED) [ "$rc" = 0 ] ;; *) [ "$rc" = 1 ] ;; esac \
        || { fail "$name: exit $rc does not match its result $want"; report_ok=0; }
    # The checkout went back to main, clean, so the next script of a session
    # (make verify-device runs four) can report from it.
    [ "$(git -C "$CLONE" rev-parse --abbrev-ref HEAD)" = main ] && [ -z "$(git -C "$CLONE" status --porcelain)" ] \
        || { fail "$name: the clone is on $(git -C "$CLONE" rev-parse --abbrev-ref HEAD) or dirty, not back on a clean main"; pr_ok=0; }
    # The report as its branch carries it.
    git -C "$CLONE" switch -q "$branch" 2>/dev/null || true
    if [ ! -f "$CLONE/$rel" ]; then
        fail "$name: $rel was not written"
        report_ok=0
    elif ! out="$(bash "$CLONE/tools/bench/validate-report.sh" "$rel" --allow-fixture-raw 2>&1)"; then
        fail "$name: $rel does not validate: $out"
        report_ok=0
    fi
    # Every raw file of the run is listed with its own hash.
    for raw in "$T/runs/$topic"/raw/*; do
        sha="$(sha256sum "$raw" | cut -d' ' -f1)"
        grep -qE "^\| \`docs/measurements/raw/$topic-$DATE/$(basename "$raw")\` \| [0-9]+ \| $sha \| (committed|owner) \|$" "$CLONE/$rel" 2>/dev/null \
            || { fail "$name: raw file $(basename "$raw") is not listed with sha256 $sha"; report_ok=0; }
    done
    pushed="$(git -C "$REMOTE" rev-parse -q --verify "refs/heads/$branch" || true)"
    [ -n "$pushed" ] && [ "$pushed" = "$(git -C "$CLONE" rev-parse -q --verify "refs/heads/$branch")" ] \
        || { fail "$name: $branch was not pushed to the bare remote"; pr_ok=0; }
    [ -n "$pushed" ] && [ "$(git -C "$REMOTE" rev-parse "$pushed^")" = "$HEAD_SHA" ] \
        || { fail "$name: the bench commit's parent is not the build measured"; pr_ok=0; }
    grep -q "^pr create --base main --head $branch --title bench: $topic $DATE ($want) --body-file " "$GH_LOG" \
        || { fail "$name: the fake gh saw no 'pr create --base main --head $branch'"; pr_ok=0; }
    git -C "$CLONE" switch -q main
    printf 'bench-pr: %-30s %-27s %-10s report %s, pr %s\n' "$name" "$topic" "$want" \
        "$([ "$report_ok" = 1 ] && echo ok || echo FAILED)" "$([ "$pr_ok" = 1 ] && echo ok || echo FAILED)"
done <<< "$CASES"
git -C "$CLONE" switch -q main

# No report and no PR body carries the ssh target or the server host.
LEAKS="$( (for b in "$T"/pr-body-*.md; do cat "$b"; done
    for topic in $(printf '%s\n' "$CASES" | cut -d'|' -f2); do
        git -C "$REMOTE" show "bench/$DATE-$topic:docs/measurements/$topic-$DATE.md" 2>/dev/null || true
    done) | grep -cE 'endpoint-b\.example|bench-host\.example|@' || true)"
BODIES="$(find "$T" -maxdepth 1 -name 'pr-body-*.md' | wc -l | tr -d ' ')"
if [ "$LEAKS" = 0 ] && [ "$BODIES" = "$(printf '%s\n' "$CASES" | grep -c .)" ]; then
    echo "bench-pr: CHORUS_SECOND_ENDPOINT=owner@endpoint-b.example and the server host appear in no report and no PR body ($BODIES bodies read)"
else
    fail "the ssh target or server host leaked: $LEAKS line(s) across the reports and $BODIES PR bodies"
fi

# The free-run report updated the baseline to hardware, pointing at itself.
FREE_RUN_BASELINE="$(git -C "$REMOTE" show "bench/$DATE-rig3-free-run:docs/measurements/free-run-baseline.conf" 2>/dev/null || true)"
if printf '%s\n' "$FREE_RUN_BASELINE" | grep -qx 'source = hardware' \
    && printf '%s\n' "$FREE_RUN_BASELINE" | grep -qx "established_by = docs/measurements/rig3-free-run-$DATE.md" \
    && printf '%s\n' "$FREE_RUN_BASELINE" | grep -qx "series = docs/measurements/raw/rig3-free-run-$DATE/paired.offsets"; then
    echo "bench-pr: the free-run PR records a hardware baseline citing its own report and paired series"
else
    fail "the free-run PR's baseline is not source = hardware citing its report and series: $FREE_RUN_BASELINE"
fi

# The soak's three-day log is over the committed limit: hashed, kept by the owner.
# shellcheck disable=SC2016 # the backticks are literal Markdown in the report
if git -C "$REMOTE" show "bench/$DATE-product6-soak:docs/measurements/product6-soak-$DATE.md" \
    | grep -qE '^\| `docs/measurements/raw/product6-soak-'"$DATE"'/local.log` \| [0-9]+ \| [0-9a-f]{64} \| owner \|$' \
    && ! git -C "$REMOTE" cat-file -e "bench/$DATE-product6-soak:docs/measurements/raw/product6-soak-$DATE/local.log" 2>/dev/null; then
    echo "bench-pr: the soak's three-day log is hashed in the report and not committed (over the 16 MiB limit)"
else
    fail "the soak's three-day log was not handled as hashed-only"
fi

# --- a goal's view: every open bench/* PR validates -------------------------------
N="$(printf '%s\n' "$CASES" | grep -c .)"
(cd "$CLONE" && CHORUS_BENCH_GH="$T/fake-gh" CHORUS_BENCH_ALLOW_FIXTURE_RAW=1 \
    bash tools/bench/validate-open-prs.sh) > "$T/open-prs.log" 2>&1 || true
VALID="$(grep -c ': valid (' "$T/open-prs.log" || true)"
if [ "$VALID" = "$N" ]; then
    echo "bench-pr: validate-open-prs.sh found all $N open bench/* PRs valid"
else
    fail "validate-open-prs.sh found $VALID of $N valid; its output:"
    sed 's/^/    /' "$T/open-prs.log" | tail -n 20
fi
# Without the test-only flag every PR whose raw data includes a committed fixture
# is refused by name (the guard against a fixture posing as a capture), and the
# seven whose raw data is only generated here (the soak, the ten-minute run,
# the delay-log shape, the over-rate, the device-loss, the decode-cost and the
# EMBEDDED-5 bring-up runs) still validate.
GENERATED_ONLY=7
(cd "$CLONE" && CHORUS_BENCH_GH="$T/fake-gh" bash tools/bench/validate-open-prs.sh) \
    > "$T/open-prs-strict.log" 2>&1 || true
INVALID="$(grep -c ': INVALID$' "$T/open-prs-strict.log" || true)"
STILL_VALID="$(grep -c ': valid (' "$T/open-prs-strict.log" || true)"
if [ "$INVALID" = "$((N - GENERATED_ONLY))" ] && [ "$STILL_VALID" = "$GENERATED_ONLY" ] \
    && [ "$(grep -c 'is byte-identical to a committed fixture' "$T/open-prs-strict.log")" = "$INVALID" ]; then
    echo "bench-pr: without the test-only flag the $INVALID PRs carrying a committed fixture as raw data are refused by name"
else
    fail "validate-open-prs.sh without the flag: $INVALID invalid, $STILL_VALID valid; its output:"
    sed 's/^/    /' "$T/open-prs-strict.log" | tail -n 20
fi

# --- refusals of the report half ---------------------------------------------------
new_run sound2-ten-minute
delay_log "$RUN/raw/ten-minute-run.log" 620
echo "dirt" > "$CLONE/untracked-change.txt"
if (cd "$CLONE" && bench_env bash tools/ten-minute-run.sh --report-from "$RUN") > "$T/dirty.log" 2>&1; then
    fail "a dirty tree was reported"
elif grep -q 'BENCH REPORT REFUSED' "$T/dirty.log" && grep -q 'uncommitted changes' "$T/dirty.log"; then
    echo "bench-pr: a dirty tree is refused by name"
else
    fail "a dirty tree was not refused by name: $(tail -n 3 "$T/dirty.log")"
fi
rm -f "$CLONE/untracked-change.txt"
git -C "$CLONE" commit -q --allow-empty -m "an unpushed commit"
sed -i "s/^build = .*/build = $(git -C "$CLONE" rev-parse HEAD)/" "$RUN/bench-run.conf"
if (cd "$CLONE" && bench_env bash tools/ten-minute-run.sh --report-from "$RUN") > "$T/unpushed.log" 2>&1; then
    fail "an unpushed commit was reported"
elif grep -q 'is not a commit on origin/main' "$T/unpushed.log"; then
    echo "bench-pr: an unpushed commit is refused by name"
else
    fail "an unpushed commit was not refused by name: $(tail -n 3 "$T/unpushed.log")"
fi
git -C "$CLONE" reset -q --hard origin/main

# Without CHORUS_BENCH_PR the report is written and nothing is published.
sed -i "s/^build = .*/build = $HEAD_SHA/" "$RUN/bench-run.conf"
BEFORE="$(wc -l < "$GH_LOG")"
(cd "$CLONE" && env CHORUS_SKIP_BUILD=1 CARGO_TARGET_DIR="$TARGET_DIR" CHORUS_BENCH_GH="$T/fake-gh" \
    CHORUS_BENCH_ALLOW_FIXTURE_RAW=1 bash tools/ten-minute-run.sh --report-from "$RUN") > "$T/nopr.log" 2>&1 || true
if [ -f "$CLONE/docs/measurements/sound2-ten-minute-$DATE-2.md" ] \
    && [ "$(git -C "$CLONE" rev-parse --abbrev-ref HEAD)" = main ] \
    && [ "$(wc -l < "$GH_LOG")" = "$BEFORE" ]; then
    echo "bench-pr: without CHORUS_BENCH_PR the report is written (as -2, the name being taken) and nothing is committed or opened"
else
    fail "without CHORUS_BENCH_PR: $(tail -n 3 "$T/nopr.log")"
fi

# A failing hardware run still reaches the repository: a start-fill log with its
# start-fill event gone grades FAIL, exits non-zero, and its report and PR are
# written and opened all the same.
git -C "$CLONE" clean -fdq
new_run sound2-start-fill
grep -v 'kind=start-fill' "$BFIX/start-fill-and-log-shape.log" > "$RUN/raw/start-fill-and-log-shape.log"
printf 'client_exit = 0\n' > "$RUN/raw/run-status.txt"
set +e
(cd "$CLONE" && bench_env bash tools/start-fill-and-log-shape.sh --report-from "$RUN") > "$T/fail.log" 2>&1
rc=$?
set -e
FAIL_REL="docs/measurements/sound2-start-fill-$DATE-2.md"
if [ "$rc" = 1 ] \
    && git -C "$REMOTE" show "bench/$DATE-sound2-start-fill-2:$FAIL_REL" 2>/dev/null | grep -q '^Result: FAIL: ' \
    && grep -q "^pr create --base main --head bench/$DATE-sound2-start-fill-2 --title bench: sound2-start-fill $DATE (FAIL) " "$GH_LOG" \
    && [ "$(git -C "$CLONE" rev-parse --abbrev-ref HEAD)" = main ] \
    && git -C "$CLONE" switch -q "bench/$DATE-sound2-start-fill-2" \
    && bash "$CLONE/tools/bench/validate-report.sh" "$FAIL_REL" --allow-fixture-raw > /dev/null; then
    echo "bench-pr: a failing device run exits 1 and still writes its FAIL report and opens its PR"
else
    fail "a failing device run: exit $rc; $(tail -n 3 "$T/fail.log")"
fi
git -C "$CLONE" switch -q main

echo
if [ "$FAILURES" -eq 0 ]; then
    echo "bench-pr: every bench entry point writes a validating report and opens its PR from fixture captures"
    exit 0
fi
echo "bench-pr: $FAILURES check(s) failed"
exit 1
