//! The committed sync cross-check vectors, and how they are made.
//!
//! One `.expected` file per committed scenario, under
//! `fixtures/sync/crosscheck/`. Each carries what the Rust sync core did with
//! that scenario, exchange by exchange: the inputs, the sample the filter
//! SELECTED out of its window, the filtered offset it returned, and what the
//! servo decided.
//!
//! # Why a file and not an assertion
//!
//! The same reason `fixtures/protocol/` is files. A second implementation of
//! the sync core - the ESP32-S3 endpoint's C mirror - has to be held to what
//! the first one does, and it cannot be held to it by calling it. The playout
//! error series says whether a loop converged; these say HOW, which is the
//! difference between two implementations that agree and two that happen to
//! land in the same place.
//!
//! Two suites read them and neither writes them:
//!
//! - `crates/sync/tests/crosscheck_vectors.rs` asserts regenerating reproduces
//!   every committed file byte for byte, so a vector cannot drift from the
//!   Rust implementation;
//! - `firmware/tests/test_sync.c` asserts the C endpoint reproduces every value
//!   in them, so the second implementation cannot drift from the first.
//!
//! Like `make measure-fixtures`, `make sync-vectors` is for changing a scenario
//! and never for making a red assertion green.

use std::fs;
use std::path::{Path, PathBuf};

use crate::scenario::Scenario;
use crate::servo::ServoAction;
use crate::sim::run_recorded;

/// Where the committed scenarios live.
pub fn scenario_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/sync")
}

/// Where a scenario's cross-check vector is committed.
pub fn vector_path(scenario_path: &Path) -> PathBuf {
    let stem = scenario_path
        .file_stem()
        .expect("a scenario file has a stem")
        .to_string_lossy()
        .into_owned();
    scenario_dir()
        .join("crosscheck")
        .join(format!("{}.expected", stem))
}

/// Every committed scenario, sorted, so the output is stable across machines.
pub fn scenario_files() -> Vec<PathBuf> {
    let dir = scenario_dir();
    let mut paths: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("{} is unreadable: {}", dir.display(), e))
        .map(|entry| entry.expect("readable directory entry").path())
        .filter(|path| path.extension().and_then(|e| e.to_str()) == Some("cfg"))
        .collect();
    paths.sort();
    paths
}

/// The cross-check vector for one scenario, as text.
///
/// Every floating-point value is written with Rust's shortest round-tripping
/// decimal, which `strtod` on the other side parses back to the identical
/// double. The file is therefore readable in a diff AND exact, which is what
/// the measurement fixtures' `.params` files already established as the shape
/// this repository wants.
pub fn vector_text(scenario_path: &Path) -> String {
    let text = fs::read_to_string(scenario_path)
        .unwrap_or_else(|e| panic!("{} is unreadable: {}", scenario_path.display(), e));
    let scenario = Scenario::parse(&text)
        .unwrap_or_else(|e| panic!("{} does not parse: {}", scenario_path.display(), e));
    let (result, records) = run_recorded(&scenario.config)
        .unwrap_or_else(|e| panic!("{} is refused: {}", scenario_path.display(), e));

    let file_name = scenario_path
        .file_name()
        .expect("a file name")
        .to_string_lossy()
        .into_owned();
    let bound = scenario.error_bound_ns;
    let settle_index = result.settle_index(bound);

    let mut out = String::new();
    out.push_str("# chorus sync cross-check vector. GENERATED by `make sync-vectors`.\n");
    out.push_str("#\n");
    out.push_str("# What the Rust sync core did with the scenario named below, exchange by\n");
    out.push_str("# exchange. crates/sync/tests/crosscheck_vectors.rs asserts regenerating\n");
    out.push_str("# reproduces this file byte for byte; firmware/tests/test_sync.c asserts the\n");
    out.push_str("# C endpoint reproduces every value in it. Neither test writes this file.\n");
    out.push_str("#\n");
    out.push_str("# Doubles are written as the shortest decimal that round-trips, so strtod on\n");
    out.push_str("# the other side recovers the identical double and the comparison is exact.\n");
    out.push('\n');
    out.push_str(&format!("scenario = {}\n", scenario.name));
    out.push_str(&format!("source = fixtures/sync/{}\n", file_name));
    out.push_str(&format!("error_bound_ns = {}\n", bound));
    out.push_str(&format!("steps = {}\n", result.samples.len()));
    out.push_str(&format!("exchanges = {}\n", result.exchanges));
    out.push_str(&format!("hard_resyncs = {}\n", result.hard_resyncs));
    out.push_str(&format!(
        "final_correction_ppm = {}\n",
        result.final_correction_ppm
    ));
    out.push_str(&format!(
        "settled = {}\n",
        if settle_index.is_some() { "yes" } else { "no" }
    ));
    out.push_str(&format!(
        "settle_index = {}\n",
        settle_index
            .map(|i| i.to_string())
            .unwrap_or_else(|| "none".to_string())
    ));
    out.push_str(&format!(
        "settle_time_ns = {}\n",
        result
            .settle_time_ns(bound)
            .map(|t| t.to_string())
            .unwrap_or_else(|| "none".to_string())
    ));
    out.push_str(&format!(
        "peak_after_settle_ns = {}\n",
        result.max_abs_error_after(settle_index.unwrap_or(0))
    ));
    out.push_str(&format!("max_abs_error_ns = {}\n", result.max_abs_error()));
    out.push_str(&format!("first_error_ns = {}\n", result.samples[0].error_ns));
    out.push_str(&format!(
        "last_error_ns = {}\n",
        result.samples[result.samples.len() - 1].error_ns
    ));

    out.push_str("\n[exchanges]\n");
    out.push_str(
        "# index at_ns rtt_ns offset_estimate_ns filtered_offset_ns selected_at_ns \
         selected_rtt_ns selected_offset_ns tier correction_ppm_or_step_ns\n",
    );
    for record in &records {
        let (tier, value) = match record.action {
            ServoAction::Fine { correction_ppm } => ("fine", correction_ppm),
            ServoAction::HardResync { step_ns } => ("hard-resync", step_ns),
        };
        out.push_str(&format!(
            "{} {} {} {} {} {} {} {} {} {}\n",
            record.index,
            record.at_ns,
            record.rtt_ns,
            record.offset_estimate_ns,
            record.filtered_offset_ns,
            record.selected.at_ns,
            record.selected.rtt_ns,
            record.selected.offset_ns,
            tier,
            value
        ));
    }
    out
}

/// Write every vector, creating the directory if it is not there.
pub fn write_all() {
    let dir = scenario_dir().join("crosscheck");
    fs::create_dir_all(&dir)
        .unwrap_or_else(|e| panic!("{} is not creatable: {}", dir.display(), e));
    for path in scenario_files() {
        let target = vector_path(&path);
        let text = vector_text(&path);
        fs::write(&target, &text)
            .unwrap_or_else(|e| panic!("{} is not writable: {}", target.display(), e));
        println!("wrote {} ({} bytes)", target.display(), text.len());
    }
}
