//! The house simulation report, `docs/measurements/sim-house-8-rooms.md`.
//!
//! Written by `cargo run --release -p chorus-sync --bin chorus-sim-house`
//! from the committed houses, so the report and the model cannot drift: every
//! parameter it lists is read from the same [`HouseConfig`] that ran.

use std::fmt::Write as _;

use crate::house::{ClassStats, HouseConfig, HouseResult, PairClass, Transport};
use crate::jitter::JitterModel;

fn us(ns: i64) -> String {
    format!("{:.1} us", ns as f64 / 1_000.0)
}

fn bound(ns: i64) -> String {
    if ns >= 1_000_000 {
        format!("< {} ms", ns / 1_000_000)
    } else {
        format!("< {} ms", ns as f64 / 1_000_000.0)
    }
}

fn jitter_text(model: &JitterModel) -> String {
    match *model {
        JitterModel::None => "none".to_string(),
        JitterModel::Uniform { max_us } => format!("uniform on [0, {} us]", max_us),
        JitterModel::Exponential { mean_us } => {
            format!("exponential, mean {} us (capped at 10x)", mean_us)
        }
        JitterModel::Burst {
            mean_us,
            enter_prob,
            exit_prob,
            burst_scale_us,
            burst_shape,
        } => format!(
            "burst: quiet exponential mean {} us; enter {} / exit {} per packet; \
             burst Lomax scale {} us, shape {} (capped at 50 ms)",
            mean_us, enter_prob, exit_prob, burst_scale_us, burst_shape
        ),
    }
}

fn class_of(result: &HouseResult, class: PairClass) -> &ClassStats {
    result
        .classes
        .iter()
        .find(|c| c.class == class)
        .expect("every class is present in the committed house")
}

/// The whole report, as Markdown.
pub fn report(
    build_sha: &str,
    switched: (&HouseConfig, &HouseResult),
    routed: (&HouseConfig, &HouseResult),
) -> String {
    let (h, r) = switched;
    let (hr, rr) = routed;
    let mut o = String::new();
    let post_settle_s = (h.duration_ms - h.settle_ms) / 1_000;

    let _ = writeln!(
        o,
        "# House-scale sync simulation: 8 rooms, {} endpoints",
        h.endpoints.len()
    );
    o.push('\n');
    o.push_str("Source: simulation\n");
    let _ = writeln!(o, "Build measured: `{}`", build_sha);
    o.push_str("Date: 2026-09-30\n");
    o.push_str(
        "Generated by: `cargo run --release -p chorus-sync --bin chorus-sim-house -- --build <sha> \
         --out docs/measurements/sim-house-8-rooms.md`\n",
    );
    o.push('\n');
    o.push_str(
        "**THIS IS A SIMULATION AND NOT TIMING EVIDENCE** (BRIEF.md section 3.1 rule 3). Every \
         number below is what the chorus sync model does with the ASSUMED parameters listed here; \
         none was measured on a device, a network or a speaker. It says the servo logic holds \
         BRIEF.md section 2.2's bounds in the model at house scale; whether the real system does \
         is for the measurement rig to say.\n\n",
    );

    o.push_str("## What was run\n\n");
    let _ = writeln!(
        o,
        "Two houses, identical except for their network links (a test asserts it): \
         `config/sim-house/8-rooms-switched.house` ({}) and \
         `config/sim-house/8-rooms-routed.house` ({}). Each endpoint is one run of the \
         single-client simulator (`crates/sync/src/sim.rs`) with its own crystal, path, jitter \
         stream, wander stream and servo, all against the one server timeline; the server is \
         passive (it only timestamps), so the runs are independent. Seed {}, {} s per run, \
         {} ms steps, one exchange every {} ms.",
        h.network,
        hr.network,
        h.seed,
        h.duration_ms / 1_000,
        h.step_ms,
        h.sync_interval_ms
    );
    o.push('\n');
    o.push_str(
        "**Inter-device error** for a pair at a true time is the difference of the two \
         endpoints' modelled playout errors (playout position minus the server timeline) at \
         that time. **Settling:** ",
    );
    let _ = writeln!(
        o,
        "the first {} s of every run is excluded from every statistic, the same acquisition \
         window the real rig excludes (`sync_hour_settle_seconds = 60`, `config/sync.conf`); \
         every endpoint acquires with one hard resync on its first exchange and none after \
         (asserted). Statistics pool |inter-device error| over every post-settle step ({} s, \
         10 ms apart) of every pair in the class; p50 and p95 are nearest rank.",
        h.settle_ms / 1_000,
        post_settle_s
    );
    o.push('\n');

    o.push_str("## Result: the switched house against BRIEF.md section 2.2\n\n");
    o.push_str("| class | pairs | p50 | p95 | max | BRIEF acceptable | aspirational | result |\n");
    o.push_str("|---|---|---|---|---|---|---|---|\n");
    for class in &r.classes {
        let _ = writeln!(
            o,
            "| {} | {} | {} | {} | {} | {} | {} | {} |",
            class.class.label(),
            class.pairs,
            us(class.p50_ns),
            us(class.p95_ns),
            us(class.max_ns),
            bound(class.class.acceptable_ns()),
            bound(class.class.aspirational_ns()),
            class.verdict()
        );
    }
    o.push('\n');
    o.push_str(
        "Result is graded on the max: \"pass\" means every post-settle sample of every pair in \
         the class is under BRIEF's acceptable bound; \"also inside aspirational\" means under \
         the aspirational one too. Same-room rows use \"Stereo pair / same room\" (the theater \
         set is also \"Surround inter-channel (later)\", the same numbers); cross-room rows use \
         \"Multiroom music, different rooms\". `crates/sync/tests/house_regression.rs` pins \
         every row inside the acceptable bound.\n\n",
    );

    o.push_str("## Switched versus routed (P3)\n\n");
    let _ = writeln!(
        o,
        "The same house with the speakers routed through the firewall (P3 option b) instead of \
         on a segment with a server leg (option b'). Links only; everything else is identical."
    );
    o.push('\n');
    o.push_str(
        "| class | switched p50 | switched p95 | switched max | switched result | routed p50 \
         | routed p95 | routed max | routed result |\n",
    );
    o.push_str("|---|---|---|---|---|---|---|---|---|\n");
    for class in PairClass::ALL {
        let (s, t) = (class_of(r, class), class_of(rr, class));
        let _ = writeln!(
            o,
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} |",
            class.label(),
            us(s.p50_ns),
            us(s.p95_ns),
            us(s.max_ns),
            s.verdict(),
            us(t.p50_ns),
            us(t.p95_ns),
            us(t.max_ns),
            t.verdict()
        );
    }
    o.push('\n');
    let peak = |res: &HouseResult, house: &HouseConfig, t: Transport| -> i64 {
        res.endpoints
            .iter()
            .enumerate()
            .filter(|(i, _)| house.transport(*i) == t)
            .map(|(_, e)| e.peak_error_after_settle_ns)
            .max()
            .unwrap_or(0)
    };
    let _ = writeln!(
        o,
        "Largest single-endpoint |playout error| against the server timeline after settling \
         (what an absolute reference such as video would see): wired {} switched and {} routed; \
         Wi-Fi {} switched and {} routed.",
        us(peak(r, h, Transport::Wired)),
        us(peak(rr, hr, Transport::Wired)),
        us(peak(r, h, Transport::Wireless)),
        us(peak(rr, hr, Transport::Wireless))
    );
    o.push('\n');

    let (sw, rw) = (
        class_of(r, PairClass::CrossRoomWired),
        class_of(rr, PairClass::CrossRoomWired),
    );
    let all_acceptable = rr.classes.iter().all(|c| c.within_acceptable());
    let same_room_aspirational = [PairClass::StereoPair, PairClass::TheaterSet]
        .iter()
        .all(|c| class_of(rr, *c).within_aspirational());
    let worst_same_room = class_of(rr, PairClass::StereoPair)
        .max_ns
        .max(class_of(rr, PairClass::TheaterSet).max_ns);
    let _ = writeln!(
        o,
        "What it implies for P3, still as a simulation and not timing evidence. The hop's \
         constant delay cancels in the offset estimate. Its constant asymmetry biases every \
         routed endpoint's offset by half of it, the same for every endpoint behind the hop, so \
         it cancels between them: the Wi-Fi / Wi-Fi row, whose link gains only the hop's constant \
         delay and asymmetry, does not move. It would not cancel between a routed endpoint and one that \
         is not routed (a standing offset of half the hop's asymmetry, 30 us here) and it shows \
         against an absolute reference (the single-endpoint peaks above). What does move \
         inter-device error in the model is the hop's QUEUEING on a trunk shared with house \
         traffic: wired cross-room p95 goes from {} to {} and max from {} to {}, because the \
         heavier queue leaks into the offset of even the least-queued exchange in the window. \
         The routed house is {} BRIEF.md section 2.2's acceptable bounds; the same-room classes \
         {} the 0.2 ms aspirational bound (worst same-room max {}). So the model says the cost \
         of option b is the shared trunk's queueing, which is what option b' removes, and the \
         size of that queueing (a 250 us mean here) is ASSUMED: the routed-versus-L2 measurement \
         in `docs/proposals/P3-speaker-network.md` is still what decides K35.",
        us(sw.p95_ns),
        us(rw.p95_ns),
        us(sw.max_ns),
        us(rw.max_ns),
        if all_acceptable {
            "inside all of"
        } else {
            "OUTSIDE some of"
        },
        if same_room_aspirational {
            "stay inside"
        } else {
            "go above"
        },
        us(worst_same_room)
    );
    o.push('\n');

    o.push_str(
        "The cross-room wired / Wi-Fi row is dominated by the Wi-Fi link's ASSUMED 300 us path \
         asymmetry: it biases a Wi-Fi endpoint's offset by 150 us that no wired endpoint shares, \
         which is most of that row's p50. That is the model's reading of why an asymmetric \
         radio path matters more than its jitter, and the parameter WIFI-7 has to measure.\n\n",
    );

    o.push_str("## Models and parameters (every value ASSUMED unless cited)\n\n");
    let _ = writeln!(
        o,
        "- Server crystal {} ppm; endpoint crystals as listed below (spread over BRIEF.md \
         section 6's +/- 20 to 50 ppm); every crystal wanders as a random walk of {} ppm per \
         square root of a second (about {:.1} ppm over the run).",
        h.server_ppm,
        h.endpoints[0].wander_ppm_per_sqrt_s,
        h.endpoints[0].wander_ppm_per_sqrt_s * ((h.duration_ms / 1_000) as f64).sqrt()
    );
    let _ = writeln!(
        o,
        "- Servo: the real client's SYNC-4 constants (`config/sync.conf`, asserted equal): \
         kp {}, ki {}, window {}, smoothing {}, hard resync at {} us, clamp {} ppm.",
        h.servo.kp,
        h.servo.ki,
        h.servo.filter_window,
        h.servo.smoothing_alpha,
        h.servo.hard_resync_threshold_ns / 1_000.0,
        h.servo.max_correction_ppm
    );
    o.push_str(
        "- Each endpoint's initial epoch offset is uniform in +/- 50 ms from its own stream; its \
         seed is the house seed plus its index through one SplitMix64 step.\n",
    );
    for (label, house) in [("switched", h), ("routed", hr)] {
        for link in &house.links {
            let _ = writeln!(
                o,
                "- {} link `{}` ({}): base {} us one way, return minus forward {} us plus the \
                 endpoint's trim, jitter {}.",
                label,
                link.name,
                link.transport.name(),
                link.base_one_way_delay_us,
                link.path_asymmetry_us,
                jitter_text(&link.jitter)
            );
        }
    }
    o.push_str(
        "- Sources: the router hop's \"tens of microseconds idle\" is the planning research's own \
         ASSUMED figure \
         (https://github.com/NSchatz/chorus/blob/535ed2816b5735153ac81c52a235024aa806f2b5/.claude/goals/2026-09-chorus-research/research-platform-network.md \
         section 4.2); the Wi-Fi burst model is `fixtures/sync/07-wifi-burst.cfg`'s, ASSUMED \
         until WIFI-7's characterization on hardware; the 50 ms burst cap is half the client's \
         100 ms round-trip admission bound (`max_rtt_us`, `config/sync.conf`). The models are \
         recorded in `docs/decisions/0006-sync-simulator-and-servo.md`.\n",
    );
    o.push_str(
        "- Not modelled: DAC, amplifier and acoustic delay; the real client's round-trip \
         admission and staleness rules; packet loss and reordering; the server's own clock \
         wander (common to every endpoint, so it cancels in inter-device error); correlation \
         between endpoints' network delays (each path is independent).\n\n",
    );

    o.push_str("## Scenario list: the room layout (ASSUMED)\n\n");
    o.push_str(
        "The owner's room list, with which rooms have copper, is an open Needs item; this is a \
         plausible K75-scale house, not the owner's.\n\n",
    );
    o.push_str("| room | set | endpoint | link | crystal ppm | asymmetry trim us |\n");
    o.push_str("|---|---|---|---|---|---|\n");
    for e in &h.endpoints {
        let _ = writeln!(
            o,
            "| {} | {} | {} | {} | {} | {} |",
            e.room,
            e.set.name(),
            e.id,
            e.link,
            e.client_ppm,
            e.asymmetry_trim_us
        );
    }
    o.push('\n');
    let wired_pairs: usize = r.classes.iter().map(|c| c.pairs).sum();
    let _ = writeln!(
        o,
        "{} pairs in all. The grouped house (every room playing together) is the cross-room \
         classes; the bonded sets are the same-room classes.",
        wired_pairs
    );
    o
}
