//! The latency-growth simulation report, `docs/measurements/latency-growth-sim.md`.
//!
//! Written by `cargo run --release -p chorus-sync --bin chorus-sim-latency`
//! from the committed scenarios, so the report and the model cannot drift:
//! every parameter it lists is read from the same [`LatencyScenario`] that
//! ran, and `crates/sync/tests/latency_growth.rs` regenerates it and compares
//! it with the committed file.

use std::fmt::Write as _;

use crate::house::{HouseConfig, Transport, CROSS_ROOM_ACCEPTABLE_NS, CROSS_ROOM_ASPIRATIONAL_NS};
use crate::latency_sim::{LatencyRun, LatencyScenario};

/// One scenario's inputs and its two runs.
pub struct ScenarioRuns<'a> {
    /// The scenario.
    pub scenario: &'a LatencyScenario,
    /// The house its endpoints come from.
    pub house: &'a HouseConfig,
    /// The plan's run.
    pub stretch: &'a LatencyRun,
    /// The negative control's run.
    pub naive: &'a LatencyRun,
}

/// Pitch change of a rate deviation `r`, in cents.
pub fn cents(r: f64) -> f64 {
    1200.0 * (1.0 + r).log2()
}

fn ms(ns: f64) -> String {
    format!("{:.3} ms", ns / 1e6)
}

fn us(ns: f64) -> String {
    format!("{:.1} us", ns / 1e3)
}

fn verdict(run: &LatencyRun) -> String {
    let f = run.failures();
    if f.is_empty() {
        "PASS".to_string()
    } else {
        format!("FAIL: {}", f.join("; "))
    }
}

/// The smallest lead (play-at stamp minus arrival) over the chunks `pick`
/// selects, in ns.
fn min_lead(
    run: &LatencyRun,
    pick: impl Fn(&crate::latency_sim::ChunkRecord) -> Option<f64>,
) -> f64 {
    run.chunks
        .iter()
        .filter_map(|c| pick(c).map(|arrival| c.play_at_ns as f64 - arrival))
        .fold(f64::MAX, f64::min)
}

fn link_text(house: &HouseConfig, id: &str) -> String {
    let e = house
        .endpoints
        .iter()
        .find(|e| e.id == id)
        .expect("the run found it");
    let link = house.link(&e.link).expect("validated");
    format!(
        "`{}` (room {}, link `{}`: {}, base {} us one way)",
        id,
        e.room,
        link.name,
        link.transport.name(),
        link.base_one_way_delay_us
    )
}

/// The whole report, as Markdown.
pub fn report(build_sha: &str, build_note: &str, runs: &[ScenarioRuns<'_>]) -> String {
    let mut o = String::new();
    o.push_str("# Latency growth without a glitch (K94): simulation\n\n");
    o.push_str("Source: simulation\n");
    let _ = writeln!(o, "Build measured: `{}`", build_sha);
    let _ = writeln!(o, "Build note: {}", build_note);
    o.push_str("Date: 2026-10-01\n");
    o.push_str(
        "Generated by: `cargo run --release -p chorus-sync --bin chorus-sim-latency -- --build <sha> \
         --note <text> --out docs/measurements/latency-growth-sim.md`\n\n",
    );
    o.push_str(
        "**THIS IS A SIMULATION AND NOT TIMING EVIDENCE** (BRIEF.md section 3.1 rule 3). Every \
         number below is what the chorus latency-growth model does with the ASSUMED parameters \
         listed here; none was measured on a device, a network or a speaker, and nobody listened \
         to it. It says the plan in `crates/sync/src/latency_grow.rs` meets the glitch criterion \
         in the model; whether a real room hears no glitch is for a listening test and the \
         measurement rig to say.\n\n",
    );

    o.push_str("## What was run\n\n");
    o.push_str(
        "A line-in (ADR 0066) on a wired endpoint plays in its own room at the local latency \
         L_local. At the join time the server learns a second room has joined the group and asks \
         the plan for the group latency L_group. The plan time-stretches the source (plays it \
         slightly slower, by a raised-cosine ramp of the rate, a hold at the bound, and the \
         mirror ramp) so the stamp offset (play-at minus capture instant) grows to L_group while \
         every output chunk stays contiguous on the server timeline. The joining room is sent \
         every chunk from the join and starts with the first that arrives in time at a latency \
         its tier can start at. In the wired scenario the room later leaves and the plan shrinks \
         the latency back by the same mechanism, the rate reversed.\n\n",
    );
    o.push_str(
        "Chunks travel as the house simulation's links model them (`config/sim-house/`, ADR \
         0048): the capture endpoint's forward path up, each player's return path down, base \
         delay plus that link's jitter model, delivered in order. The server renders an output \
         chunk once every source frame its cubic interpolator reads has arrived. The source \
         signal is the frame index itself, and cubic (Catmull-Rom) interpolation reproduces a \
         straight line exactly, so every sample the playing room hears is the source position it \
         played: the criterion below is checked on the rendered audio, frame by frame. \
         Inter-room error is the difference of the two endpoints' playout errors from the house \
         simulation's own single-client runs, sampled at each chunk's play-at instant; both \
         rooms render the same stamps, so the stamps add nothing to it by construction.\n\n",
    );

    o.push_str("## The glitch criterion\n\n");
    o.push_str(
        "For the room already playing, over the whole run: **(a)** output samples, read as \
         source positions, strictly increase with every per-frame step inside [1 - r_max, \
         1 + r_max], and no frame is inserted (a stamp gap, heard as silence) or dropped (a \
         stamp overlap); **(b)** no underrun: every chunk reaches it at least the endpoint guard \
         before its play-at stamp; **(c)** the stamp offset never moves away from where the plan \
         is heading, and every transition reaches its target; **(d)** the rate's change from one \
         chunk to the next is inside the profile's slope bound r_max pi / (2 R) per frame times \
         a chunk. For the pair once both play: |inter-room error| under BRIEF.md section 2.2's \
         \"Multiroom music, different rooms\" acceptable bound (5 ms). The same checks run on \
         the negative control, the latency set to L_group at once, which has to fail them.\n\n",
    );

    let config = runs[0].stretch.config;
    let r = config.max_rate_deviation;
    o.push_str("## The rate bound\n\n");
    let _ = writeln!(
        o,
        "r_max = {} ppm = {:.3} % = {:.3} cents. The cited threshold: the smallest mean \
         frequency difference limen trained listeners showed for steady pure tones, 0.2 % \
         ({:.2} cents) at 1 kHz (Dai and Micheyl 2011, \"Psychometric functions for pure-tone \
         frequency discrimination\", JASA 130(1), \
         https://pmc.ncbi.nlm.nih.gov/articles/PMC3155586/, read 2026-10-01). r_max is a quarter \
         of it; added to the endpoint servo's largest correction (300 ppm, `config/sync.conf`) \
         it is {:.3} cents, still under half. The threshold is for two steady tones compared \
         side by side, which is harder on the stretch than a slow glide inside music; the margin \
         is a choice (ASSUMED until a listening test). Ramp R = {} s (ASSUMED). A change of dL \
         takes dL / r_max + R: {} s per 100 ms of latency.\n",
        r * 1e6,
        r * 100.0,
        cents(r),
        cents(0.002),
        cents(r + 300e-6),
        config.ramp_frames as f64 / f64::from(config.sample_rate_hz),
        config.transition_ns(100e6) / 1e9,
    );

    for s in runs {
        let sc = s.scenario;
        let run = s.stretch;
        let fs = f64::from(run.config.sample_rate_hz);
        let chunk_ns = f64::from(run.config.chunk_frames) / fs * 1e9;
        let _ = writeln!(o, "## Scenario `{}`\n", sc.name);
        let _ = writeln!(
            o,
            "`config/sim-latency/{}.latency`. House `{}`; seed {}; {} s; {} Hz, {} ms chunks.\n",
            sc.name,
            sc.house,
            sc.seed,
            sc.duration_ms / 1_000,
            sc.sample_rate_hz,
            sc.chunk_ms
        );
        o.push_str("| parameter | value | from |\n|---|---|---|\n");
        let _ = writeln!(
            o,
            "| source (line-in, playing room) | {} | the house file, ASSUMED |",
            link_text(s.house, &sc.source)
        );
        let _ = writeln!(
            o,
            "| joining room | {} | the house file, ASSUMED |",
            link_text(s.house, &sc.joiner)
        );
        let _ = writeln!(
            o,
            "| join at | {} s | after the house's 60 s settle |",
            sc.join_at_ms as f64 / 1e3
        );
        let leave = match sc.leave_at_ms {
            Some(t) => format!("{} s", t as f64 / 1e3),
            None => "never".to_string(),
        };
        let _ = writeln!(o, "| leave at | {} | |", leave);
        let _ = writeln!(
            o,
            "| L_local | {} | ASSUMED |",
            ms(sc.l_local_us as f64 * 1e3)
        );
        let joiner = s
            .house
            .endpoints
            .iter()
            .position(|e| e.id == sc.joiner)
            .expect("the run found it");
        let wireless = s.house.transport(joiner) == Transport::Wireless;
        let l_group_from = if !wireless {
            "`config/sync.conf` `playout_latency_us`"
        } else {
            "`config/transport.conf` `wireless_playout_latency_us`"
        };
        let _ = writeln!(
            o,
            "| L_group | {} | {} |",
            ms(sc.l_group_us as f64 * 1e3),
            l_group_from
        );
        let join_from = if !wireless {
            "the local room's tier (wired): L_local"
        } else {
            "`config/transport.conf` `wireless_min_us`; reading it as the start condition is ASSUMED"
        };
        let _ = writeln!(
            o,
            "| joining room's least start latency | {} | {} |",
            ms(sc.join_min_latency_us as f64 * 1e3),
            join_from
        );
        let _ = writeln!(
            o,
            "| r_max | {} ppm | the rate bound above |",
            sc.max_rate_ppm
        );
        let _ = writeln!(o, "| ramp R | {} s | ASSUMED |", sc.ramp_ms as f64 / 1e3);
        let _ = writeln!(
            o,
            "| server processing | {} | ASSUMED |",
            us(sc.server_processing_us as f64 * 1e3)
        );
        let _ = writeln!(
            o,
            "| endpoint guard | {} | ASSUMED |",
            us(sc.endpoint_guard_us as f64 * 1e3)
        );
        o.push('\n');

        let g = &run.glitch;
        o.push_str("| result | value |\n|---|---|\n");
        let _ = writeln!(
            o,
            "| frames checked (playing room, rendered audio) | {} |",
            g.frames_checked
        );
        let _ = writeln!(
            o,
            "| (a) per-frame step, min / max | {:.9} / {:.9} |",
            g.min_step, g.max_step
        );
        let _ = writeln!(
            o,
            "| (a) frames inserted / dropped | {} / {} |",
            g.inserted_frames, g.overlapped_frames
        );
        let _ = writeln!(
            o,
            "| (a) largest \\|rate\\| | {:.1} ppm ({:.3} cents) |",
            g.max_abs_rate * 1e6,
            cents(g.max_abs_rate)
        );
        let _ = writeln!(
            o,
            "| (a) largest \\|rendered - planned position\\| | {:e} frames |",
            g.max_render_error
        );
        let lead = min_lead(run, |c| Some(c.play_arrival_ns));
        let _ = writeln!(o, "| (b) underruns (playing room) | {} |", g.underruns);
        let _ = writeln!(
            o,
            "| (b) least lead, play-at minus arrival (playing room) | {} (guard {}) |",
            ms(lead),
            ms(sc.endpoint_guard_us as f64 * 1e3)
        );
        let _ = writeln!(
            o,
            "| (c) offset moves away from its heading | {} |",
            g.offset_reversals
        );
        for t in &run.transitions {
            let took = t
                .reached_chunk
                .map(|k| format!("{:.2} s", (k - t.requested_chunk) as f64 * chunk_ns / 1e9))
                .unwrap_or_else(|| "never reached".to_string());
            let _ = writeln!(
                o,
                "| (c) transition {} to {} | requested at {:.2} s, took {} (planned {:.2} s) |",
                ms(t.from_ns),
                ms(t.to_ns),
                t.requested_chunk as f64 * chunk_ns / 1e9,
                took,
                run.config.transition_ns(t.to_ns - t.from_ns) / 1e9
            );
        }
        let _ = writeln!(
            o,
            "| (d) largest rate change per chunk | {:.4} ppm (bound {:.4} ppm) |",
            g.max_rate_change_per_chunk * 1e6,
            run.config.max_rate_change_per_chunk() * 1e6
        );
        if let Some(k) = run.join_start_chunk {
            let start = &run.chunks[k as usize];
            let requested = run.transitions.first().map_or(0, |t| t.requested_chunk);
            let _ = writeln!(
                o,
                "| joining room starts | {:.2} s after the join, at an offset of {} |",
                (k - requested) as f64 * chunk_ns / 1e9,
                ms(start.offset_ns)
            );
            let jlead = min_lead(run, |c| {
                if c.join_plays {
                    c.join_arrival_ns
                } else {
                    None
                }
            });
            let _ = writeln!(
                o,
                "| joining room underruns after it starts / least lead | {} / {} |",
                run.join_underruns,
                ms(jlead)
            );
        }
        if let Some(p) = run.pair {
            let _ = writeln!(
                o,
                "| inter-room error while both play: chunks, p50 / p95 / max | {}, {} / {} / {} (acceptable < {} ms, aspirational < {} ms) |",
                p.samples,
                us(p.p50_ns as f64),
                us(p.p95_ns as f64),
                us(p.max_ns as f64),
                CROSS_ROOM_ACCEPTABLE_NS / 1_000_000,
                CROSS_ROOM_ASPIRATIONAL_NS / 1_000_000
            );
        }
        let _ = writeln!(o, "| **criterion** | **{}** |", verdict(run));
        o.push('\n');

        let n = s.naive;
        let _ = writeln!(
            o,
            "Negative control (the latency set to L_group at once, no stretch): {} frames of \
             silence inserted ({}), {} underruns; **{}**.\n",
            n.glitch.inserted_frames,
            ms(n.glitch.inserted_frames as f64 / fs * 1e9),
            n.glitch.underruns,
            verdict(n)
        );
    }

    o.push_str("## What this does not show\n\n");
    o.push_str(
        "- That nobody hears it. The bound is a cited threshold with a margin, not a listening \
         test; the cubic interpolator's own artifacts are not modelled at all (the source here \
         is a straight line).\n\
         - That a Wi-Fi room can start soon. It waits for the latency to reach its tier's floor, \
         minutes at this bound (the scenario's table says how long); the decision record lists \
         the options.\n\
         - Capture-clock drift against the server timeline, gaps in the source (an overrun on \
         the capture device) and a join in the middle of a transition (the plan holds a new \
         target until the running transition ends): the decision record's follow-ups.\n\
         - Anything on a real network, endpoint or DAC.\n",
    );
    o
}
