//! chorus's chimes: short bell-like sounds generated by this code, rendered to
//! PCM in any format a stream uses.
//!
//! # Whose sound this is
//!
//! Every chime is synthesised here, from the partial tables below: no sample,
//! recording or third-party sound is in it. The rendered audio is chorus's own
//! work under the repository's licence, MIT OR Apache-2.0 (`docs/chimes.md`
//! lists each one).
//!
//! # How a chime is made
//!
//! A chime is one or more **strikes**. A strike is a fundamental frequency and
//! a set of **partials**, each a frequency ratio, an amplitude and an
//! exponential decay time constant: additive synthesis, the textbook model of
//! a struck bell or bar (higher partials die faster). Each strike opens with a
//! short linear attack ([`ATTACK_MS`]) so it starts from zero and does not
//! click, and the whole chime closes with a linear release ([`RELEASE_MS`])
//! that reaches exactly zero on the last frame, so it ends at digital silence.
//! The mix is then scaled so its peak is exactly [`PEAK`] of full scale
//! (-6.02 dBFS, at or below the ASSUMED -6 dBFS ceiling), and the same signal
//! is written to every channel.
//!
//! # Deterministic on every machine
//!
//! A golden digest has to hold on any platform, and `f64::sin` and
//! `f64::exp` are the platform's libm, which is free to differ in the last
//! bit. So no libm function is called: a partial's phase is exact integer
//! arithmetic (frequency in millihertz times the frame index, modulo the rate
//! in millihertz), and sine and the decay exponential are evaluated by
//! [`sin_turns`] and [`exp_neg`] from `+`, `-`, `*` and `/` alone, which IEEE
//! 754 defines to the bit and Rust never fuses. `tests/chimes.rs` pins the
//! 48 kHz s16le render of each chime with an FNV-1a 64 digest.

use std::fmt;

/// The attack of every strike, milliseconds. ASSUMED: 5 ms is short enough to
/// sound struck and long enough not to click; not measured.
pub const ATTACK_MS: u64 = 5;

/// The release at the end of every chime, milliseconds. ASSUMED.
pub const RELEASE_MS: u64 = 300;

/// The peak of every render, as a fraction of full scale: -6.02 dBFS, at or
/// below the ASSUMED -6 dBFS ceiling (a chime over music must not be the
/// loudest thing in the room by surprise).
pub const PEAK: f64 = 0.5;

/// The sample rates and channel counts a render accepts: the audio wire's
/// (`docs/protocol.md`, `chorus_protocol::{MIN_SAMPLE_RATE_HZ,
/// MAX_SAMPLE_RATE_HZ, MAX_CHANNELS}`).
pub const MIN_RATE_HZ: u32 = 8_000;
/// See [`MIN_RATE_HZ`].
pub const MAX_RATE_HZ: u32 = 384_000;
/// See [`MIN_RATE_HZ`].
pub const MAX_CHANNELS: u16 = 8;

/// A PCM sample layout: the three the audio wire carries, by the same names
/// (`chorus_protocol::SampleFormat`; this crate depends on no other).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PcmFormat {
    /// Signed 16-bit little-endian.
    S16Le,
    /// Signed 24-bit little-endian, packed in 3 bytes.
    S24Le,
    /// 32-bit IEEE float little-endian, full scale 1.0.
    F32Le,
}

impl PcmFormat {
    /// The wire name, `pcm_s16le` and so on.
    pub fn name(self) -> &'static str {
        match self {
            PcmFormat::S16Le => "pcm_s16le",
            PcmFormat::S24Le => "pcm_s24le",
            PcmFormat::F32Le => "pcm_f32le",
        }
    }

    /// The format a wire name names.
    pub fn from_name(name: &str) -> Option<PcmFormat> {
        [PcmFormat::S16Le, PcmFormat::S24Le, PcmFormat::F32Le]
            .into_iter()
            .find(|f| f.name() == name)
    }

    /// Bytes per sample.
    pub fn bytes(self) -> usize {
        match self {
            PcmFormat::S16Le => 2,
            PcmFormat::S24Le => 3,
            PcmFormat::F32Le => 4,
        }
    }
}

/// Why a render was refused.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenderError {
    /// A sample rate outside 8 000 to 384 000 Hz.
    Rate(u32),
    /// A channel count outside 1 to 8.
    Channels(u16),
}

impl fmt::Display for RenderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RenderError::Rate(r) => write!(f, "a chime renders at 8000 to 384000 Hz, not {r}"),
            RenderError::Channels(c) => write!(f, "a chime renders to 1 to 8 channels, not {c}"),
        }
    }
}

impl std::error::Error for RenderError {}

/// One partial of a strike.
struct Partial {
    /// Frequency as a multiple of the fundamental, in thousandths.
    ratio_milli: u64,
    /// Relative amplitude.
    amp: f64,
    /// Exponential decay time constant, milliseconds.
    decay_ms: u64,
}

/// One strike.
struct Strike {
    /// When it starts, milliseconds from the chime's start.
    at_ms: u64,
    /// Fundamental, millihertz.
    fundamental_mhz: u64,
    /// Its partials.
    partials: &'static [Partial],
}

const fn p(ratio_milli: u64, amp: f64, decay_ms: u64) -> Partial {
    Partial {
        ratio_milli,
        amp,
        decay_ms,
    }
}

/// A church-bell-like spectrum: hum, prime, minor-third tierce, quint,
/// nominal, superquint and octave nominal, the higher ones dying faster.
const BELL: &[Partial] = &[
    p(500, 0.6, 3000),
    p(1000, 1.0, 1800),
    p(1200, 0.7, 1400),
    p(1500, 0.35, 1000),
    p(2000, 0.8, 900),
    p(3000, 0.25, 500),
    p(4000, 0.12, 300),
];

/// A struck free bar's spectrum (the modes of a doorbell or tubular chime
/// bar sit near 1, 2.756 and 5.404 times the fundamental).
const BAR: &[Partial] = &[p(1000, 1.0, 1600), p(2756, 0.35, 600), p(5404, 0.12, 250)];

/// A soft, nearly harmonic tone for a short notification.
const SOFT: &[Partial] = &[p(1000, 1.0, 900), p(2000, 0.25, 450), p(3000, 0.08, 250)];

// Equal-tempered pitches from A4 = 440 Hz, in millihertz.
const A4: u64 = 440_000;
const C5: u64 = 523_251;
const E5: u64 = 659_255;
const G5: u64 = 783_991;

/// A named chime.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Chime {
    /// `bell`: one bell strike on A4, 3 s.
    Bell,
    /// `ding-dong`: two bar strikes, E5 then C5, 2.8 s; the doorbell.
    DingDong,
    /// `triad`: C5, E5, G5 in quick succession, soft, 1.8 s; a notification.
    Triad,
}

/// Every chime, in the order `docs/chimes.md` lists them.
pub const CHIMES: [Chime; 3] = [Chime::Bell, Chime::DingDong, Chime::Triad];

impl Chime {
    /// Its name: what a group's `source` names as `chime:<name>`.
    pub fn name(self) -> &'static str {
        match self {
            Chime::Bell => "bell",
            Chime::DingDong => "ding-dong",
            Chime::Triad => "triad",
        }
    }

    /// The chime a name names.
    pub fn from_name(name: &str) -> Option<Chime> {
        CHIMES.into_iter().find(|c| c.name() == name)
    }

    /// Its length, milliseconds.
    pub fn duration_ms(self) -> u64 {
        match self {
            Chime::Bell => 3000,
            Chime::DingDong => 2800,
            Chime::Triad => 1800,
        }
    }

    fn strikes(self) -> &'static [Strike] {
        const fn s(at_ms: u64, fundamental_mhz: u64, partials: &'static [Partial]) -> Strike {
            Strike {
                at_ms,
                fundamental_mhz,
                partials,
            }
        }
        const BELL_STRIKES: &[Strike] = &[s(0, A4, BELL)];
        const DING_DONG: &[Strike] = &[s(0, E5, BAR), s(650, C5, BAR)];
        const TRIAD: &[Strike] = &[s(0, C5, SOFT), s(150, E5, SOFT), s(300, G5, SOFT)];
        match self {
            Chime::Bell => BELL_STRIKES,
            Chime::DingDong => DING_DONG,
            Chime::Triad => TRIAD,
        }
    }

    /// Frames in a render at `rate_hz`.
    pub fn frames(self, rate_hz: u32) -> usize {
        (self.duration_ms() * u64::from(rate_hz) / 1000) as usize
    }

    /// The mono signal at `rate_hz`, peak exactly [`PEAK`], last sample 0.
    pub fn mono(self, rate_hz: u32) -> Vec<f64> {
        let rate = u64::from(rate_hz);
        let frames = self.frames(rate_hz);
        let attack = (ATTACK_MS * rate / 1000).max(1) as f64;
        let release = (RELEASE_MS * rate / 1000).max(1) as f64;
        let modulus = rate * 1000; // one cycle, in millihertz-frames
        let mut out = vec![0.0f64; frames];
        for strike in self.strikes() {
            let start = (strike.at_ms * rate / 1000) as usize;
            for partial in strike.partials {
                let f_mhz = strike.fundamental_mhz * partial.ratio_milli / 1000;
                // The decay as a per-frame factor: e^(-m/decay) is the
                // factor to the m-th power, kept by one multiplication a frame
                // (deterministic, and far cheaper than an exponential a frame).
                let decay_frames = (partial.decay_ms * rate) as f64 / 1000.0;
                let per_frame = exp_neg(1.0 / decay_frames);
                let mut env = 1.0f64;
                for (m, slot) in out.iter_mut().skip(start).enumerate() {
                    let m64 = m as u64;
                    let turns = ((f_mhz * m64) % modulus) as f64 / modulus as f64;
                    let att = if (m as f64) < attack {
                        m as f64 / attack
                    } else {
                        1.0
                    };
                    *slot += partial.amp * att * env * sin_turns(turns);
                    env *= per_frame;
                }
            }
        }
        // The release, reaching exactly 0 on the last frame.
        for (n, slot) in out.iter_mut().enumerate() {
            let left = (frames - 1 - n) as f64;
            if left < release {
                *slot *= left / release;
            }
        }
        let peak = out.iter().fold(0.0f64, |a, &x| a.max(x.abs()));
        let gain = if peak > 0.0 { PEAK / peak } else { 1.0 };
        for x in &mut out {
            // `+ 0.0` turns a negative zero (a negative sample times the
            // release's final 0) into +0.0, so the last f32 sample is all
            // zero bytes: digital silence in every format.
            *x = *x * gain + 0.0;
        }
        out
    }
}

/// Render `chime` to interleaved little-endian PCM: `rate_hz` frames per
/// second, `channels` identical channels, in `format`.
pub fn render(
    chime: Chime,
    rate_hz: u32,
    channels: u16,
    format: PcmFormat,
) -> Result<Vec<u8>, RenderError> {
    if !(MIN_RATE_HZ..=MAX_RATE_HZ).contains(&rate_hz) {
        return Err(RenderError::Rate(rate_hz));
    }
    if !(1..=MAX_CHANNELS).contains(&channels) {
        return Err(RenderError::Channels(channels));
    }
    Ok(encode(&chime.mono(rate_hz), channels, format))
}

/// Interleave a mono signal (full scale 1.0) into `channels` identical
/// channels of `format`: the second half of [`render`], for a caller that
/// renders a chime once and sends it in several formats.
pub fn encode(mono: &[f64], channels: u16, format: PcmFormat) -> Vec<u8> {
    let channels = channels.max(1);
    let mut out = Vec::with_capacity(mono.len() * usize::from(channels) * format.bytes());
    for &x in mono {
        let mut sample = [0u8; 4];
        let bytes: &[u8] = match format {
            PcmFormat::S16Le => {
                let v = (x * 32_767.0).round().clamp(-32_768.0, 32_767.0) as i16;
                sample[..2].copy_from_slice(&v.to_le_bytes());
                &sample[..2]
            }
            PcmFormat::S24Le => {
                let v = (x * 8_388_607.0).round().clamp(-8_388_608.0, 8_388_607.0) as i32;
                sample[..3].copy_from_slice(&v.to_le_bytes()[..3]);
                &sample[..3]
            }
            PcmFormat::F32Le => {
                sample.copy_from_slice(&(x as f32).to_le_bytes());
                &sample[..]
            }
        };
        for _ in 0..channels {
            out.extend_from_slice(bytes);
        }
    }
    out
}

/// `sin(2 pi turns)` for `turns` in `[0, 1)`, from basic arithmetic only.
///
/// Folded by symmetry onto `[0, pi/2]`, then the Taylor series to the x^17
/// term, whose truncation error there is below 5e-14: far under a 24-bit
/// step (1.2e-7), and the same bits on every IEEE 754 machine.
pub fn sin_turns(turns: f64) -> f64 {
    let (sign, mut x) = if turns >= 0.5 {
        (-1.0, turns - 0.5)
    } else {
        (1.0, turns)
    };
    if x > 0.25 {
        x = 0.5 - x;
    }
    let theta = x * std::f64::consts::TAU;
    let t2 = theta * theta;
    let mut term = theta;
    let mut sum = theta;
    let mut k = 1.0;
    for _ in 0..8 {
        term = -term * t2 / ((k + 1.0) * (k + 2.0));
        sum += term;
        k += 2.0;
    }
    sign * sum
}

/// `e^-x` for `x >= 0`, from basic arithmetic only.
///
/// `x = k ln 2 + r` with `r` in `[0, ln 2)`; `e^-r` by its Taylor series
/// (20 terms, error below 1e-20), times `2^-k` built exactly from the
/// exponent bits; 0 once `2^-k` would be subnormal.
pub fn exp_neg(x: f64) -> f64 {
    if x.is_nan() || x <= 0.0 {
        return 1.0;
    }
    let k = (x / std::f64::consts::LN_2).floor();
    if k >= 1022.0 {
        return 0.0;
    }
    let r = x - k * std::f64::consts::LN_2;
    let mut term = 1.0;
    let mut sum = 1.0;
    for i in 1..=20 {
        term = -term * r / f64::from(i);
        sum += term;
    }
    sum * f64::from_bits(((1023 - k as u64) & 0x7ff) << 52)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_arithmetic_matches_libm_closely() {
        for i in 0..10_000 {
            let turns = f64::from(i) / 10_000.0;
            let want = (turns * std::f64::consts::TAU).sin();
            assert!((sin_turns(turns) - want).abs() < 1e-12, "sin at {turns}");
        }
        for i in 0..10_000 {
            let x = f64::from(i) / 100.0;
            let want = (-x).exp();
            assert!(
                (exp_neg(x) - want).abs() <= want * 1e-12 + 1e-300,
                "exp at {x}"
            );
        }
        assert_eq!(exp_neg(0.0), 1.0);
        assert_eq!(exp_neg(1e6), 0.0);
    }

    #[test]
    fn names_round_trip() {
        for c in CHIMES {
            assert_eq!(Chime::from_name(c.name()), Some(c));
        }
        assert_eq!(Chime::from_name("gong"), None);
        assert_eq!(PcmFormat::from_name("pcm_s24le"), Some(PcmFormat::S24Le));
    }
}
