"""aiochorus: an async client for the chorus control plane (HTTP and server-sent events).

Vendored inside the Home Assistant integration; this directory is its one source
location. It imports nothing from Home Assistant and takes an injected
``aiohttp.ClientSession``. The contract it speaks is ``docs/control-plane.md``.
"""

from .client import (
    ChorusClient,
    ControllerEventStream,
    EventStream,
    VisualizerStream,
    VoiceAudio,
    VoiceEventStream,
)
from .commands import (
    announce,
    autoplay,
    encode_volume,
    firmware_install,
    group_volume,
    group_volume_step,
    join,
    mute,
    playback,
    quiet_hours_enabled,
    sound,
    take,
    voice_enabled,
    voice_start,
    voice_stop,
    volume,
    volume_from_level,
    volume_step,
)
from .errors import (
    ChorusCommandError,
    ChorusConnectionError,
    ChorusError,
    ChorusProtocolError,
    ChorusRefusedError,
    ChorusUnsupportedError,
    ChorusVoiceRouteError,
)
from .metrics import Metrics, SpeakerMetrics
from .models import (
    BUTTONS,
    LONG_PRESS,
    PRESS,
    Announcement,
    AutoplayRule,
    ControllerEvent,
    FirmwareImage,
    Group,
    InputLabel,
    NowPlaying,
    SavedGroup,
    ServerInfo,
    Sound,
    Speaker,
    SpeakerFirmware,
    State,
    VisualizerFrame,
    VoiceRun,
    VoiceWake,
    WakeWord,
    Zone,
)
from .sse import SSEParser

__all__ = [
    "BUTTONS",
    "LONG_PRESS",
    "PRESS",
    "Announcement",
    "AutoplayRule",
    "ChorusClient",
    "ChorusCommandError",
    "ChorusConnectionError",
    "ChorusError",
    "ChorusProtocolError",
    "ChorusRefusedError",
    "ChorusUnsupportedError",
    "ChorusVoiceRouteError",
    "ControllerEvent",
    "ControllerEventStream",
    "EventStream",
    "FirmwareImage",
    "Group",
    "InputLabel",
    "Metrics",
    "NowPlaying",
    "SSEParser",
    "SavedGroup",
    "ServerInfo",
    "Sound",
    "Speaker",
    "SpeakerFirmware",
    "SpeakerMetrics",
    "State",
    "VisualizerFrame",
    "VisualizerStream",
    "VoiceAudio",
    "VoiceEventStream",
    "VoiceRun",
    "VoiceWake",
    "WakeWord",
    "Zone",
    "announce",
    "autoplay",
    "encode_volume",
    "firmware_install",
    "group_volume",
    "group_volume_step",
    "join",
    "mute",
    "playback",
    "quiet_hours_enabled",
    "sound",
    "take",
    "voice_enabled",
    "voice_start",
    "voice_stop",
    "volume",
    "volume_from_level",
    "volume_step",
]
