/* What the endpoint's DSP chain costs, timed where it runs (goal 12;
 * docs/decisions/, "the DSP chain's cost on the chip").
 *
 * The chain (chorus/dsp.h, run in the playout path by chorus/endpoint_dsp.h)
 * has never been timed on an ESP32-S3, and BRIEF section 3.1 rule 3 allows no
 * headroom claim without a bench report. This is the endpoint half of that
 * measurement, after decode_cost.h's pattern: a few named configurations of
 * the chain are each run over one second of a generated 48 kHz stereo signal,
 * in the playout path's own 32-frame calls, and only the chain calls are timed
 * on the clock handed in (the monotonic one on the chip; a test hands in a
 * fake or the host's). The result is frames per second and the fraction of one
 * core real time would take.
 *
 * A figure is only ever about a chain that produced the right audio. The
 * output is summed into a checksum (its energy and four pseudo-random +-1
 * projections, in double) and compared with the reference the HOST computed
 * for the same input (chorus_dsp_cost_reference, regenerated by
 * firmware/tests/test_console.c). The comparison has a tolerance rather than
 * decode-cost's exact hash because the chain calls libm (log10f and expf per
 * frame in the night compressor, double sin, cos and pow in the designs), and
 * newlib on the chip need not round those as glibc does: a last-place
 * difference is not wrong audio, a stage skipped or a filter misdesigned is.
 * A projection onto a random +-1 sequence measures the NORM of the error, so a
 * narrow cut that barely moves the energy still moves it by the cut's own
 * size. The exact FNV-1a hash is reported beside it (`bit_exact`) as
 * information, never as the gate.
 *
 * A figure taken this way on an ESP32-S3 is a hardware measurement only when
 * the bench script (tools/decode-cost-run.sh, bench session S6) takes it and
 * writes its report; on a host it is host evidence and nothing more. */

#ifndef CHORUS_DSP_COST_H
#define CHORUS_DSP_COST_H

#include <stddef.h>
#include <stdint.h>

#include "chorus/decode_cost.h"
#include "chorus/dsp.h"

/* The stream every configuration runs: 48 kHz stereo (FL, FR), one second. */
#define CHORUS_DSP_COST_RATE_HZ 48000u
#define CHORUS_DSP_COST_FRAMES 48000u
/* Frames per chain call: the playout path's CHORUS_ENDPOINT_DSP_BLOCK_FRAMES,
 * so the per-call overhead is the one the endpoint pays. */
#define CHORUS_DSP_COST_BLOCK 32u
/* The configurations, in reply order: flat, all-on, sub, two-way. */
#define CHORUS_DSP_COST_CONFIGS 4u
/* Projections in the checksum. */
#define CHORUS_DSP_COST_PROJECTIONS 4u
/* The largest deviation from the host's checksum that still counts as the
 * same audio, relative to the output's RMS norm. ASSUMED: 1e-4 (-80 dB),
 * about a thousand times the error a last-place libm difference makes, and
 * far below what a stage skipped makes: the host test drops the mildest
 * room-EQ filter of the all-on configuration and the night compressor, and
 * each is refused with the deviation it printed. */
#define CHORUS_DSP_COST_TOLERANCE 1e-4

/* What one run of a configuration's output sums to. */
typedef struct {
    uint64_t fnv1a64;
    double energy;
    double projection[CHORUS_DSP_COST_PROJECTIONS];
} chorus_dsp_cost_sums_t;

typedef struct {
    const char *name;
    uint32_t outputs;
    uint64_t frames;
    uint64_t elapsed_ns;
    /* Chain frames per second of wall clock on this core. */
    double frames_per_s;
    /* Seconds of chain per second of audio: 0.25 means real-time playback
     * would spend a quarter of one core in the chain. */
    double cpu_fraction;
    /* This run's sums, and the largest deviation from the reference's
     * (energy relative to the reference energy, each projection relative to
     * the reference's RMS norm). */
    chorus_dsp_cost_sums_t sums;
    double deviation;
    /* deviation <= CHORUS_DSP_COST_TOLERANCE: the gate on publishing. */
    int output_matches;
    /* The FNV-1a hash of the output floats equals the host's: information. */
    int bit_exact;
} chorus_dsp_cost_t;

/* The configurations' names, CHORUS_DSP_COST_CONFIGS of them. */
extern const char *const chorus_dsp_cost_names[];

/* The host's checksums, one per configuration (firmware/src/dsp_cost.c). */
extern const chorus_dsp_cost_sums_t chorus_dsp_cost_reference[];

/* Allocates the chain object (about 72 KB). The chip binds internal RAM, where
 * the playout path's own chain lives (firmware/main/app_main.c), so the
 * figure is not a PSRAM figure. NULL: malloc and free. */
typedef void *(*chorus_dsp_cost_alloc_fn)(size_t bytes);
typedef void (*chorus_dsp_cost_free_fn)(void *p);

/* Configuration `config`'s settings and name. Returns 0, or -1 when there is
 * no such configuration. */
int chorus_dsp_cost_configure(size_t config, chorus_dsp_sound_t *sound,
                              chorus_dsp_endpoint_t *endpoint, const char **name);

/* Run a chain for `sound` and `endpoint` over the generated signal, timed on
 * `now_ns`, and compare its sums with `reference`. What chorus_dsp_cost_run
 * does for one configuration; a test hands in altered settings to see the
 * comparison refuse them. */
int chorus_dsp_cost_measure(const char *name, const chorus_dsp_sound_t *sound,
                            const chorus_dsp_endpoint_t *endpoint,
                            const chorus_dsp_cost_sums_t *reference, chorus_clock_fn now_ns,
                            chorus_dsp_cost_alloc_fn alloc, chorus_dsp_cost_free_fn release,
                            chorus_dsp_cost_t *out, char *detail, size_t detail_len);

/* Run configuration `config` (0..CHORUS_DSP_COST_CONFIGS-1) once, timed on
 * `now_ns`. Returns 0 with `out` filled, or -1 with `detail` naming what was
 * wrong (no such configuration, a chain the library refused, no memory). */
int chorus_dsp_cost_run(size_t config, chorus_clock_fn now_ns, chorus_dsp_cost_alloc_fn alloc,
                        chorus_dsp_cost_free_fn release, chorus_dsp_cost_t *out, char *detail,
                        size_t detail_len);

#endif /* CHORUS_DSP_COST_H */
