#!/usr/bin/env bash
# Regenerate fixtures/schedule: the TZif zoneinfo files crates/schedule's tests read, and the
# glibc zdump listing they are cross-checked against (`make schedule-fixtures`, never the gate).
#
# Inputs: the host's tz database (tzdata, public domain, https://www.iana.org/time-zones and
# https://data.iana.org/time-zones/tz-link.html, read 2026-10-01). The `.fat.tzif` files are the
# host's compiled zoneinfo copied as they are; the `.slim.tzif` files are zic's `-b slim` build of
# the host's `tzdata.zi`, which keep only the transitions the footer TZ string cannot express, so
# the footer governs 2026 and the reader's footer path is exercised. The version and hashes of
# what was committed are in fixtures/README.md; a different tzdata is a reviewed diff, not drift.
. "$(dirname "$0")/lib.sh"

zoneinfo=/usr/share/zoneinfo
criterion="regenerate fixtures/schedule from the host tz database"
command -v zic > /dev/null || missing_prerequisite "$criterion" "zic" "the tz database compiler (Debian: libc-bin)"
command -v zdump > /dev/null || missing_prerequisite "$criterion" "zdump" "the tz dump tool (Debian: libc-bin)"
[ -f "$zoneinfo/tzdata.zi" ] || missing_prerequisite "$criterion" "$zoneinfo/tzdata.zi" "the tzdata package"

out="$REPO_ROOT/fixtures/schedule"
zones=(America/New_York Europe/Berlin Australia/Lord_Howe Asia/Jerusalem America/Nuuk Pacific/Apia Etc/UTC)
slim="$(mktemp -d)"
trap 'rm -rf "$slim"' EXIT
zic -b slim -d "$slim" "$zoneinfo/tzdata.zi"
mkdir -p "$out"
for z in "${zones[@]}"; do
    n="${z//\//_}"
    cp "$zoneinfo/$z" "$out/$n.fat.tzif"
    cp "$slim/$z" "$out/$n.slim.tzif"
done
version="$(sed -n 's/^# version //p' "$zoneinfo/tzdata.zi")"
{
    echo "# glibc zdump -v over the committed fat files' source zones (tzdata $version),"
    echo "# regenerated by tools/schedule-fixtures.sh; read by crates/schedule/tests/tzif_fixtures.rs."
    echo "# Each line: the second before and the second of a transition, UT = local."
    for z in America/New_York Europe/Berlin Australia/Lord_Howe Asia/Jerusalem America/Nuuk; do
        zdump -v -c 2026,2028 "$z" | command grep -E ' 202[67] UT'
        zdump -v -c 2100,2101 "$z" | command grep -E ' 2100 UT'
    done
    zdump -v -c 2011,2012 Pacific/Apia | command grep -E ' 2011 UT'
} > "$out/zdump.txt"
say "fixtures/schedule: tzdata $version, ${#zones[@]} zones fat and slim, zdump.txt"
